### ISSUE TITLE
Add "Differences between feline and X" to README

### ISSUE THREAD

**Issue by wcpines** [Famiu/feline.nvim#1]
[Galaxyline](https://github.com/glepnir/galaxyline.nvim) and [Lualine](https://github.com/hoob3rt/lualine.nvim) seem similar.  I'd love to know at a glance how they differ from Feline

**Comment by Famiu** [comment]
I just added a [Why Feline?](https://github.com/Famiu/feline.nvim/#why-feline) section in the readme, check it out and tell me if that satisfies your needs.
