### ISSUE TITLE
[Feature] add table for custom status lines

### ISSUE THREAD

**Issue by rebelot** [famiu/feline.nvim#107]
Would it be possible to have something like this?

```lua
custom_components = {
  {
    condition = table similar to force_inactives
    components = active/inactive component table
  },
  {
    condition = table similar to force_inactives
    components = active/inactive component table
  }, ...
}
```

This way, it is possible to differentiate between the statusline of inactive regular buffers and statusline of sidebar plugins. 
But also will give full control on active/inactive statusline for every filetype.
At the moment it is possible to achieve this behavior by working on top of the provided interface, but I think having this built in would be a cool addition.

alternatively, exposing a function `require('feline').create_statusline(component_list)` would be useful to manually create `WinEnter` `WinLeave` autocommands

**Comment by famiu** [comment]
Take a look at the `enabled` component value, that should do what you want

**Comment by rebelot** [comment]
Yes, I'm aware that this feature can be built using the `enabled` component, however, that would require writing conditions for every component, also I think it is less efficient than an autocommand implementation.

Feel free to close this if you don't think it's worth it :)

**Comment by famiu** [comment]
> Yes, I'm aware that this feature can be built using the `enabled` component, however, that would require writing conditions for every component, also I think it is less efficient than an autocommand implementation.
> 
> Feel free to close this if you don't think it's worth it :)

I've thought of adding component groups (components that share a same set of configurations so they don't have to be redefined) before, but honestly I don't think it's worth adding because of the complexity it adds to the codebase. Plus it can confuse new users as well. So honestly, it's not a feature I wish to implement. Sorry but I'm going to have to close this.

**Comment by rebelot** [comment]
I support the component groups feature, I would be really happy if you'll find some time in the future to implement this

**Comment by famiu** [comment]
> I support the component groups feature, I would be really happy if you'll find some time in the future to implement this

Like I said, I don't really plan on adding it right now due to the complexity it would add to the codebase, and it might make configuration more confusing for newbies. But then again I might change my mind and add this
