### ISSUE TITLE
[Bug] Custom background color is not respected for disabled sections

### ISSUE THREAD

**Issue by PetarMetodiev** [famiu/feline.nvim#109]
**Neovim version**
The output of `nvim --version`.
```sh
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info

```

**Feline version**
`0.2`

**Describe the bug**
`colors.bg` does not work as default background color for disabled providers when there are more than one sections. It seems like it doesn't matter if the section is active or not - the issue still persists.

**To Reproduce**
Minimal feline config:
```lua
local colors = { bg = '#449ef0' }

local components = {
  active = {}
}

table.insert(components.active, {})
table.insert(components.active, {})

table.insert(components.active[1], { 
    provider = 'test',
    enabled = function()
      return false
    end
  })
table.insert(components.active[2], {})

require('feline').setup({
    colors = colors,
    components = components
  })

```
...and it looks like this:
![image](https://user-images.githubusercontent.com/6378306/134785201-809690e1-bd0c-4d88-95ea-353b2188fe82.png)

**Expected behavior**
When a section is disabled, it should receive the colors set in `colors.bg` and `colors.fg`.
A real world example is when using the `git_branch` provider - it works as expected when inside a git repo, but not when not in a git repo.

**Does this error occur in the minimal init file?**

> Use the following commands to download the minimal init file provided by Feline:
> `curl -fLO https://raw.githubusercontent.com/famiu/feline.nvim/master/minimal_init.lua`
> 
> Modify the file to your needs (if necessary), then load Neovim using:
> `nvim --noplugin -u minimal_init.lua`
> 
> And check if your issue still occurs.

Yes, the issue still persists, but the colors are different:
![image](https://user-images.githubusercontent.com/6378306/134785402-fe7aadf7-a658-480f-b12f-4b52f6623c94.png)

**Provide modified minimal_init.lua**

<details>
<summary>Modified `minimal_init.lua`</summary>

```lua

-- Minimal init file to run Feline with the most basic functionality
-- Run from Feline top-level directory using:
-- nvim --noplugin -u minimal_init.lua

local function load_plugins()
    local packer = require('packer')
    local use = packer.use

    packer.reset()
    packer.init {
        package_root = '/tmp/nvim/site/pack',
        git = {
            clone_timeout = -1
        }
    }

    use 'wbthomason/packer.nvim'
    use {
        'famiu/feline.nvim',

        -- If you wish to use the develop branch, uncomment the next line
        -- branch = 'develop',

        -- If you wish to use a specific version of Feline, uncomment the next line
        -- tag = 'v0.1', -- replace 'v0.1' with your version number

        requires = {
            {
                'lewis6991/gitsigns.nvim',
                requires = { 'nvim-lua/plenary.nvim' },
                config = function()
                    require('gitsigns').setup()
                end
            },
            'kyazdani42/nvim-web-devicons'
        }
    }

    packer.sync()
end

_G.load_config = function()
    vim.opt.termguicolors = true

    -- Replace this part of the config with whatever Feline configuration you're using
    local colors = { bg = '#449ef0', fg = '#ffffff' }

    local components = {
      active = {},
      inactive = {}
    }

    table.insert(components.active, {})
    table.insert(components.active, {})

    table.insert(components.active[1], { 
      provider = 'test',
      enabled = function()
        return false
      end
    })
    table.insert(components.active[2], { })

    require('feline').setup({
      colors = colors,
      components = components
    })
end

local install_path = '/tmp/nvim/site/pack/packer/start/packer.nvim'

vim.opt.packpath = {'/tmp/nvim/site'}

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
end

load_plugins()
vim.api.nvim_command('autocmd User PackerComplete ++once lua load_config()')
```
</details>

**Screenshots**
Already provided.

**Additional context**
I cannot think of any.

**Comment by famiu** [comment]
Does a67897405f23cce54473d2afbc1a7df63688b815 fix your issue?

**Comment by PetarMetodiev** [comment]
Wooow! Thanks for the fast response!
This did fix my issue. 
It seems it is in the develop branch though. Do you have any plans when the develop branch will be merged? One of the reasons feline resonated with me was the semantic versioning and plans for stability.
Anyway, keep up the good work. You are awesome!

**Comment by famiu** [comment]
> Wooow! Thanks for the fast response!

Np

> This did fix my issue.
> It seems it is in the develop branch though. Do you have any plans when the develop branch will be merged? One of the reasons feline resonated with me was the semantic versioning and plans for stability.

As soon as #106 is resolved, there will be a 0.2.1 release

> Anyway, keep up the good work. You are awesome!

Thanks, I'll try my best

**Comment by famiu** [comment]
@PetarMetodiev 0.2.1 is out btw

**Comment by famiu** [comment]
Just realized that after fixing this, the section gaps can no longer be customized to have any color other than the default bg

**Comment by famiu** [comment]
By the way, I recently pushed a breaking change that allows customizing the gaps between sections, so using the bg color is no longer the default behavior either, so you might have to change your config on the next Feline update if you're using the develop branch
