### ISSUE TITLE
[Bug] Config for making inactive statuslines as thin lines doesnt work

### ISSUE THREAD

**Issue by siduck76** [famiu/feline.nvim#113]
**Neovim version**
The output of `nvim --version`.
```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
**Feline version**
What version of Feline are you using? If you're using the `develop` branch instead of a release then please clarify that as well.
Master branch 

**Describe the bug**
Making inactive statuslines as thin lines doesnt work 

** Minimal init.lua config **
```
-- Install packer
local install_path = vim.fn.stdpath "data" .. "/site/pack/packer/start/packer.nvim"

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
   vim.fn.execute("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
end

local use = require("packer").use
require("packer").startup(function()
   use "wbthomason/packer.nvim"
   use "famiu/feline.nvim"
end)

require("feline").setup {
   preset = "noicon",
}

-- Initialize the components table
local components = {
   active = {},
   inactive = {},
}

table.insert(components.active, {})
table.insert(components.inactive, {})

local nvim_exec = vim.api.nvim_exec

-- Get highlight of inactive statusline by parsing the style, fg and bg of VertSplit
local InactiveStatusHL = {
   fg = nvim_exec("highlight VertSplit", true):match "guifg=(#[0-9A-Fa-f]+)" or "#444444",
   bg = nvim_exec("highlight VertSplit", true):match "guibg=(#[0-9A-Fa-f]+)" or "#1E1E1E",
   style = nvim_exec("highlight VertSplit", true):match "gui=(#[0-9A-Fa-f]+)" or "",
}

-- Add underline to inactive statusline highlight style
-- in order to have a thin line instead of the statusline
if InactiveStatusHL.style == "" then
   InactiveStatusHL.style = "underline"
else
   InactiveStatusHL.style = InactiveStatusHL.style .. ",underline"
end

-- Apply the highlight to the statusline
-- by having an empty provider with the highlight
components.inactive = {
   {
      {
         provider = " ",
         hl = InactiveStatusHL,
      },
   },
}
```

Screenshots : 

![image](https://user-images.githubusercontent.com/59060246/134816908-85630042-1e92-4ba6-af22-58fd72eab4aa.png)

**Comment by famiu** [comment]
you're not even setting up feline with the components table in the minimal_init. Please provide an edited version of the `minimal_init.lua` file provided by Feline instead of attempting to make your own minimal_init. Just edit the setup function in the original `minimal_init.lua` to provide the preset and components table and then see if you can reproduce the issue

**Comment by siduck76** [comment]
that minimal_init.lua doesnt work for me :/ , packer keeps looping and syncing the plugins

**Comment by siduck76** [comment]
https://user-images.githubusercontent.com/59060246/134817709-a6f1e467-265e-4abc-b08a-ab54f1accffb.mp4

maybe issue with my system

**Comment by famiu** [comment]
setting `bg` to `'NONE'` inside `InactiveStatusHL` should fix your issue

**Comment by famiu** [comment]
This should be even simpler to achieve now with the `default_hl` option in the setup function

**Comment by siduck76** [comment]
> This should be even simpler to achieve now with the `default_hl` option in the setup function

How? :D 

![image](https://user-images.githubusercontent.com/59060246/135001315-21af0cc5-8015-465f-9aa9-9a6db43b417d.png)

For now I just use this

**Comment by famiu** [comment]
> > This should be even simpler to achieve now with the `default_hl` option in the setup function
> 
> How? :D
> 
> ![image](https://user-images.githubusercontent.com/59060246/135001315-21af0cc5-8015-465f-9aa9-9a6db43b417d.png)
> 
> For now I just use this

https://github.com/famiu/feline.nvim/blob/develop/USAGE.md#thin-line-for-horizontal-splits

**Comment by siduck76** [comment]
> > > This should be even simpler to achieve now with the `default_hl` option in the setup function
> > 
> > 
> > How? :D
> > ![image](https://user-images.githubusercontent.com/59060246/135001315-21af0cc5-8015-465f-9aa9-9a6db43b417d.png)
> > For now I just use this
> 
> https://github.com/famiu/feline.nvim/blob/develop/USAGE.md#thin-line-for-horizontal-splits

didnt work for me 

![image](https://user-images.githubusercontent.com/59060246/135219343-5a5dccaf-ab2b-4f2d-a3fb-622f6e240584.png)

I got those fat inactive statuslines again!

**Comment by famiu** [comment]
are you using the development branch?

**Comment by siduck76** [comment]
> are you using the development branch?

oh yea this works ._.

**Comment by siduck76** [comment]
@famiu how do I remove the inactive statusline in nvimtree?

![image](https://user-images.githubusercontent.com/59060246/136647718-3083f8d0-56c4-48ed-9494-6ec27c1cc845.png)

Nvimtree gives a highlight group for the statusline in it 

![image](https://user-images.githubusercontent.com/59060246/136647759-2e1ce3fc-4b7d-465f-8546-75d9754a4220.png)
