### ISSUE TITLE
[Feature] How to highlight the gaps

### ISSUE THREAD

**Issue by mcchrish** [famiu/feline.nvim#116]
**Is your feature request related to a problem? Please describe.**
With this commit: https://github.com/famiu/feline.nvim/commit/a67897405f23cce54473d2afbc1a7df63688b815
The gap now respects the default bg. There should be a way to highlight the gaps.

**Describe the solution you'd like**
Add configuration for gap hl.

**Additional context**
Middle part of my inactive statusline:
<img width="564" alt="Screen Shot 2021-09-27 at 6 54 03 AM" src="https://user-images.githubusercontent.com/7200153/134826936-102e6205-2c1f-4138-b4c2-c2423959ac58.png">
It used to be the same color as all throughout.

**Comment by famiu** [comment]
You can just change the default bg

**Comment by mcchrish** [comment]
But I want a different bg for inactive.

**Comment by famiu** [comment]
> But I want a different bg for inactive.

How do you propose the gaps should be configured?

**Comment by mcchrish** [comment]
I'm thinking there should be a separate bg config for the inactive. When not specified, fallback to the `bg`.
```
{
bg = "#ffffff",
inactive_bg = "#fafafa" --optional
}

**Comment by famiu** [comment]
Just realized people could also want different colors for each section gap, so each section gap would need to be allowed to be configured differently

**Comment by PetarMetodiev** [comment]
How about making a separate provider which acts as a gap?

**Comment by famiu** [comment]
> How about making a separate provider which acts as a gap?

That's what I'm thinking too

**Comment by famiu** [comment]
After the latest commit, you should be able to achieve it by following the instructions in https://github.com/famiu/feline.nvim/blob/develop/USAGE.md#highlight-section-gaps

**Comment by famiu** [comment]
Closing this since the feature has been added
