### ISSUE TITLE
[Feature] LSP messages with lsp-status

### ISSUE THREAD

**Issue by cloggier** [famiu/feline.nvim#12]
**Is your feature request related to a problem? Please describe.**
express line can display messages from LSP which can be quite useful (https://github.com/tjdevries/express_line.nvim/blob/master/lua/el/plugins/lsp_status.lua).

**Describe the solution you'd like**
Add the same support (new provider) to feline.

**Describe alternatives you've considered**
I can imagine that being quite common use case eventually so having it provided (optionally) by plugin can help many users.

**Additional context**
Great looking plugin! I have tried galaxy line and had many problems, feline worked of the bat, thanks!

**Comment by famiu** [comment]
Sorry but I don't want to add extra dependencies to feline. And I tried to find a way to do it without `lsp_status.lua`, but it seems rather complicated. Feel free to make a pull request, though.

**Comment by cloggier** [comment]
@famiu I wonder whether this PR is of any help here at all: https://github.com/nvim-lua/lsp-status.nvim/pull/58.

**Comment by famiu** [comment]
> @famiu I wonder whether this PR is of any help here at all: [nvim-lua/lsp-status.nvim#58](https://github.com/nvim-lua/lsp-status.nvim/pull/58).

Don't see how that has anything to do with it, although I just skimmed over it. My decision is still the same, I'm avoiding too many external dependencies, and doing it without external dependencies seems complicated. But if you (or anyone else) can make a PR that does it without any external dependencies, I'll be glad to accept it

**Comment by famiu** [comment]
Since this issue has gone stale, I'm gonna close it. If someone wants this, make a pull request.
