### ISSUE TITLE
Not able to set hl fg color in file_info

### ISSUE THREAD

**Issue by bragmore** [famiu/feline.nvim#127]
After breaking changes in v0.2 I'm not able to set the file_info provider fg color anymore, no matter what I do. It simply just turn out to be white.

Is there a fix for this?

**Comment by famiu** [comment]
> After breaking changes in v0.2 I'm not able to set the file_info provider fg color anymore, no matter what I do. It simply just turn out to be white.
> 
> Is there a fix for this?

I cannot reproduce your issue, it works fine for me, can you share your config for the `file_info` provider?

**Comment by bragmore** [comment]
```file = {
     info = {
        provider = {
            name = "file_info",
                opts = {
                    type = "full-path",
         },
         file_modified_icon = "",
               hl = {
                    fg = colors.orange,
                    style = "bold",
           },
 },

**Comment by famiu** [comment]
> @famiu sure! here it is. setting hl colors for every other provider works just fine, except for file_info
> 
> Result:
> 
> ![image](https://user-images.githubusercontent.com/17138968/135626942-28711365-a5fa-4ca7-b655-6b4b44cb51d1.png)
> 
> ```lua
> local colors = require("config.colors") -- in the top of the statusline.lua config file
> file = {
>      info = {
>         provider = {
>             name = "file_info",
>             hl = {
>                  fg = colors.blue,
>                     style = "bold",
>          },
>                 opts = {
>                     type = "full-path",
>          },
>          file_modified_icon = "",
>                hl = {
>                     fg = colors.orange,
>                     style = "bold",
>            },
>  },
> ```

Why did you put `hl` inside of provider? It's supposed to be separate from provider?

**Comment by bragmore** [comment]
> > @famiu sure! here it is. setting hl colors for every other provider works just fine, except for file_info
> > Result:
> > ![image](https://user-images.githubusercontent.com/17138968/135626942-28711365-a5fa-4ca7-b655-6b4b44cb51d1.png)
> > ```lua
> > local colors = require("config.colors") -- in the top of the statusline.lua config file
> > file = {
> >      info = {
> >         provider = {
> >             name = "file_info",
> >             hl = {
> >                  fg = colors.blue,
> >                     style = "bold",
> >          },
> >                 opts = {
> >                     type = "full-path",
> >          },
> >          file_modified_icon = "",
> >                hl = {
> >                     fg = colors.orange,
> >                     style = "bold",
> >            },
> >  },
> > ```
> 
> Why did you put `hl` inside of provider? It's supposed to be separate from provider

I'm stupid, you can close this. You are completely right. Thanks for the quick reply though!
