### ISSUE TITLE
Give file_modified_icon a colour

### ISSUE THREAD

**Issue by d-miketa** [famiu/feline.nvim#130]
It should be possible to give `file_modified_icon` in `file_info` a custom colour. `bufferline` does this and it'd be nice to see the same icon & colour combo in the statusline as well as the bufferline.

**Comment by famiu** [comment]
Hmm... this will be difficult to implement from the Feline's side since providers cannot parse highlights. Technically you could just disable the `file_modified_icon` and have a separate component just for the file modified icon, which you can give a custom highlight

**Comment by famiu** [comment]
Actually, I'm going to try to implement this by separating highlight parsing from the statusline generator

**Comment by famiu** [comment]
It seems that using `WinScrolled` works as a `WinResize`

**Comment by famiu** [comment]
I'd like to clarify that this will probably take a while to implement since it'd take quite a few internal changes, so it won't make it into the `v0.3` release which is coming out quite soon
