### ISSUE TITLE
[Feature] Set default `fg` and `bg` with highlight group

### ISSUE THREAD

**Issue by EdenEast** [famiu/feline.nvim#133]
I recently switched all of my `hl` sections over to use my own defined highlight groups so that I could redefine them on `ColorScheme` events. This works great for the most part, but there is an issue setting the default `fg` and `bg` as a highlight group. Currently from what I can find these are only set in the setup function in the `colors` table. These cant be defined as a highlight group.

Having a top level optional configuration value set to some highlight group would be an option. Something like:

```lua
require("feline").setup({
  default_hl = "StatusLine", -- If this if defined then `fg` and `bg` will be taken from this highlight group
  -- ...
})
```

I am unsure that adding something to the existing `colors` option would be doable as that currently is a list of single colors to values.

If you are cureous on my current setup you can find my feline config [here](https://github.com/EdenEast/nyx/blob/4e0d3cc/config/.config/nvim/lua/eden/modules/ui/feline/init.lua) and my highlight groups are defined [here](https://github.com/EdenEast/nyx/blob/4e0d3cc/config/.config/nvim/lua/eden/modules/ui/feline/colors.lua)

There is an example of the right side of my bar

![image](https://user-images.githubusercontent.com/2746374/135737357-9c6f6686-67fb-4389-bb3f-f67194f9d13a.png)

The bg colors of the position section should be the default `StatusLine` color but it is defaulted to `colors.fg` and `colors.bg`.

**Comment by famiu** [comment]
`default_hl` as of now cannot be a string since it literally sets the definition of the `StatusLine` highlight, so what you're doing is redundant, you can just remove that part altogether since you have `StatusLine` sets

**Comment by EdenEast** [comment]
Having something like `default_hl` was a proposed solution to the issue of not being able to set `fg` and `bg` of the statusline to a highlight group. Is there a way to have the default `fg` and `bg` colors not be set by `colors.fg` and `colors.bg`?

**Comment by famiu** [comment]
> Having something like `default_hl` was a proposed solution to the issue of not being able to set `fg` and `bg` of the statusline to a highlight group. Is there a way to have the default `fg` and `bg` colors not be set by `colors.fg` and `colors.bg`?

Why would you want default `fg` and `bg` to not be set by `colors.fg` and `colors.bg`, that's literally their entire purpose? If you mean section gaps, there's an entire section in the USAGE.md for [highlighting section gaps](https://github.com/famiu/feline.nvim/blob/develop/USAGE.md#highlighting-section-gaps)

**Comment by EdenEast** [comment]
The reason that I would like to have `fg` and `bg` set to a highlight group instead of `colors.fg` and `colors.bg` is so that when a new colorscheme is applied the fg and bg are linked to a highlight group that would change. It would be reset when `reset_highlights()` is called from the autocmd on `ColorScheme`.

**Comment by famiu** [comment]
> The reason that I would like to have `fg` and `bg` set to a highlight group instead of `colors.fg` and `colors.bg` is so that when a new colorscheme is applied the fg and bg are linked to a highlight group that would change. It would be reset when `reset_highlights()` is called from the autocmd on `ColorScheme`. Currently I have everything being responsive to colorscheme changes except the default fg/bg as that is set to the static colors of `colors.fg/bg`.

Technically you can do that by setting the highlights where `fg` and `bg` are used to functions? `fg` and `bg` just exist to make life easier, you can still manually override them

**Comment by EdenEast** [comment]
I have overridden all of the hl sections of my components. The issue is with the areas that dont have a component. Looking at the `generator` these sections are highlighted using `StatusComponentDefault`. The issue is how this highlight group is defined. Looking at the definition does not check if that highlight group is defined but instead if some internal list contains it. This means that I cannot define this highlight group myself or link it to something like `StatusLine`. 

```lua
-- Return default highlight
local function defhl()
    if not M.highlights['StatusComponentDefault'] then
        add_hl('StatusComponentDefault', colors.fg, colors.bg, 'NONE')
    end

    return 'StatusComponentDefault'
end
```

Trying to set `M.highlights` to contain `StatusComponentDefault` before calling setup() does not work because the require caches that there are no components because the setup function has not been called.

Maybe checking if this highlight group is defined instead of a local list would solve the issue of the default bar highlight with no components.

**Comment by famiu** [comment]
> I have overridden all of the hl sections of my components. The issue is with the areas that dont have a component. Looking at the `generator` these sections are highlighted using `StatusComponentDefault`.

That's no longer the case in the develop branch
