### ISSUE TITLE
[Feature] Pre reset_highlights hook

### ISSUE THREAD

**Issue by EdenEast** [famiu/feline.nvim#134]
I am working on changing my feline config over to use my own defined highlight groups. These highlight groups are defined from the current applied colorscheme. In the `setup` function there is an `autocmd` defined on `ColorScheme` that calls `reset_highlights`.

I would like some way to pass a function to feline to be executed before `reset_highlights` is called. In my case I would like to update the defined highlight groups based on the new colorscheme applied before the reset call.

An alternative to this would be to have an option to disable feline from defining the autocmd so I can just define it myself. This is what I am currently doing but `reset_highlights` is called twice unnecessarily.

**Comment by famiu** [comment]
I'm thinking of adding a `highlight_reset_triggers` similar to `update_triggers`, thoughts on that?

**Comment by EdenEast** [comment]
From my understanding of update_triggers that is a list of autocmd events that would trigger the event. I am looking to execute a function before the reset is called. My use case for this would be to regenerate my highlight groups based on the colorscheme that was just applied (the one that triggered the `ColorScheme` event).

**Comment by famiu** [comment]
> From my understanding of update_triggers that is a list of autocmd events that would trigger the event. I am looking to execute a function before the reset is called. My use case for this would be to regenerate my highlight groups based on the colorscheme that was just applied (the one that triggered the `ColorScheme` event).

Setting `highlight_reset_triggers` to an empty table will disable the autocmds entirely and thus allow you to set your own

**Comment by EdenEast** [comment]
Oh yes you are correct! That would be a solution to my issue.

**Comment by famiu** [comment]
The feature has been implemented in `develop` and will be in the `v0.3` release (which is releasing very soon)

**Comment by EdenEast** [comment]
Thanks for your work!
