### ISSUE TITLE
[Bug] Show `nvim-lint` errors in the statusline too

### ISSUE THREAD

**Issue by wizard-28** [famiu/feline.nvim#140]
**Is your feature request related to a problem? Please describe.**
Feline displays native LSP warnings in the statusline just fine, but it doesn't display errors reported by external linters such as `nvim-lint`

**Describe the solution you'd like**
Add ability to show external linter warnings in the statusline

**Comment by famiu** [comment]
Feline is supposed to be minimal and I don't intend to add support for something that's not built-in to Neovim. If you want support for external linters, kindly create a provider for it yourself.
