### ISSUE TITLE
[Bug] `default_hl` overridden by component definitions

### ISSUE THREAD

**Issue by EdenEast** [famiu/feline.nvim#144]
**Neovim version**
<details>
<summary>neovim version</summary>
<pre>
NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/h54j7mavdyznrifai5dadard3z121i2s-neovim-unwrapped-master/share/nvim
"
</pre>
</details>

**Feline version**
`develop` branch commit `227566a34`

**Describe the bug**

Adding a component will not apply `default_hl` value to statusline. If there is a component defined the entire bar will default to the colors set in `colors.bg` and `colors.fg`.

**To Reproduce**
1. Open nvim `nvim --clean -u minimal_init.lua minimal_init.lua`
2. Close packer window and create a split
3. Notice that the `active` window has a component defined and is set to the default colors
   `colors.fg` and `colors.bg`
4. Notice that `inactive` window is correct with no components

**Expected behavior**
Active window's statusline would be the colors set in `default_hl` where no component exists.

**Actual behavior**
Active window's statusline is the color of `colors.fg` and `colors.bg` where no component exists

**minimal_init.lua**
```lua
local install_path = "/tmp/nvim/site/pack/packer/start/packer.nvim"
local compile_path = install_path .. "/plugin/packer_compiled.lua"
vim.opt.packpath = "/tmp/nvim/site"

local function load_plugins()
  local packer = require("packer")
  local use = packer.use

  packer.reset()
  packer.init({
    package_root = "/tmp/nvim/site/pack",
    compile_path = compile_path,
    git = { clone_timeout = -1 },
  })

  use("wbthomason/packer.nvim")
  use("edeneast/nightfox.nvim") -- have a colorscheme
  use({
    "famiu/feline.nvim",
    branch = "develop",
    requires = {
      {
        "lewis6991/gitsigns.nvim",
        requires = { "nvim-lua/plenary.nvim" },
        config = function()
          require("gitsigns").setup()
        end,
      },
      "kyazdani42/nvim-web-devicons",
    },
  })

  packer.sync()
end

_G.load_config = function()
  vim.opt.termguicolors = true
  vim.cmd("colorscheme nightfox")

  -- Replace this part of the config with whatever Feline configuration you're using
  local components = {
    active = {
      {
        { provider = "file_info" },
      },
      {},
    },
    inactive = {},
  }
  require("feline").setup({
    components = components,
    default_hl = { -- Example of flipping statusline colors
      active = {
        fg = "#1d1d1d", -- should be black
        bg = "#eeefff", -- should be white
      },
      inactive = { -- This seams to work because no components are set for `inactive`
        fg = "#1d1d1d", -- should be black
        bg = "#eeefff", -- should be white
      },
    },
  })
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
vim.api.nvim_command("autocmd User PackerComplete ++once lua load_config()")
```

**Screenshots**

![image](https://user-images.githubusercontent.com/2746374/135953794-f20572b9-d467-40ec-ba99-cebd6896f3bc.png)

**Comment by EdenEast** [comment]
I found that adding a blank component that set the `hl` group to `StatusLine` will achieve the desired effect. For an example, in the `minimal_init.lua` file changing the components table the to:

```lua
  local components = {
    active = {
      {
        { provider = "file_info", },
	{ provider = "", hl = "StatusLine"},
      },
      {},
    },
    inactive = {},
  }
```

It looks like it takes the `hl` from the last component to the next. Not sure if this is documented anywhere. Finally got my statusline's colors to be defined by the current colorscheme applied. ([commit](https://github.com/EdenEast/nyx/commit/e0f62c9b5d609215a05fa763df441caff66709b3) as an example.).

**Comment by famiu** [comment]
This is not a bug, it's intended behavior, see https://github.com/famiu/feline.nvim/blob/develop/USAGE.md#highlighting-section-gaps for more info

**Comment by famiu** [comment]
That being said, I can make components use the `default_hl` by default, the issue is, that'd prevent them from being able to set custom highlights for section gaps
