### ISSUE TITLE
Stop shifting elements when the width changes.

### ISSUE THREAD

**Issue by rafamadriz** [famiu/feline.nvim#15]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it can get really annoying.
 
Here you can see how the elements shift when the position element changes its width 
![output](https://user-images.githubusercontent.com/67771985/118554599-2f603400-b751-11eb-98ac-a9b7a6830ea0.gif)

**Describe the solution you'd like**

The components should have a fixed width and it shouldn't be affected by others components. I think that the only components that need modification are the position and probably the progress bar. Because all of the other things in the statusline are static, they never change, like the filename *(they can change but not every time you move through the file)*. The components making the whole statusline to shift are the position ones, since they can change its width when you move through the file.  
 
**Describe alternatives you've considered**

One example where this does not happen is lualine. The elements don't shift when they change its width. 
![output2](https://user-images.githubusercontent.com/67771985/118556271-32f4ba80-b753-11eb-827e-0a0c4cca64a4.gif)

Compare the two, and I think you can see how annoying it can get to have the statusline changing its position when you move through the file. However this is not a big deal, it's not like me or most people are staring at the statusline the whole time, but nonetheless it would be nice if this doesn't happen.

**Comment by famiu** [comment]
The issue with that is that there's no maximum value for line and column numbers. However, I did fix the issue in the latest commit. The problem is it assumes line numbers to have no more than 3 digits and column numbers to have no more than two digits.

Either way, I fixed the issue. Check if it works for you now so that I may close this. Unless you have a better solution for the line / column number size problem.

**Comment by rafamadriz** [comment]
Awesome thanks. 

>  The problem is it assumes line numbers to have no more than 3 digits and column numbers to have no more than two digits.

Yes, you are right, that can be a problem when opening huge files.

> Unless you have a better solution for the line / column number size problem.

I'll look into that. I think that first checking how many characters are  returned from `vim.fn.line('.')` and  `vim.fn.col('.'))` and then setting the width in base of that could be an option. 

For now this can be closed.

**Comment by famiu** [comment]
> I'll look into that. I think that first checking how many characters are returned from vim.fn.line('.') and vim.fn.col('.')) and then setting the width in base of that could be an option.
>
The line number and column number are constantly changing though, so setting the width based on that means the statusline would constantly change as well.

**Comment by famiu** [comment]
> The problem is it assumes line numbers to have no more than 3 digits and column numbers to have no more than two digits.
>
Also I worded this wrong, the providers would still work fine for numbers larger than that, but, it'd move its contents like how it used to before

**Comment by rafamadriz** [comment]
> The line number and column number are constantly changing though, so setting the width based on that means the statusline would constantly change as well, bringing us back to where we started

oh yes you're absolutely right.

What you think about first getting the total amount of lines of the file and then setting the width? I think that for the edge cases where for example opening a file with a compressed line of code with hundreds of columns shouldn't be something to worry about. As you said it would still work, just shifting the elements once again. 

The other problem with first getting the total amount of lines is that in case of opening a huge file, then the width is going to be really big even when being in the first lines of the file, making it look weird. 

But once again those are more of edge cases, maybe setting a max width. So in case of opening a big file, the elements will have a fixed wdith until a certain numbers of characters, after that it will just shift the components like before.

**Comment by rafamadriz** [comment]
Hey I've been testing and opening big files and honestly it's perfectly fine now. The annoying part was having the statusline shift on almost every line I moved. 

But now with the fixed width it only shifts when it reaches the maximum amount of characters that have been set . And this only happens every... I don't know the exact number but the point is that I have to move a lot through the file to have the statusline shift. And once again the annoying part was when it was happening every second, that was what made it so noticeable for me and annoying at moments. But hey, if it only happens every now and then, I have no problem with that.

**Comment by famiu** [comment]
> Hey I've been testing opening big files and honestly it's perfectly fine now. The annoying part was having the statusline shift on almost every line I moved.
> 
> But now with the fixed width it only shifts when it reaches the maximum amount of characters that have been set . And this only happens every... I don't know the exact number but the point is that I have to move a lot through the file to have the statusline shift. And once again the annoying part was when it was happening every second, that was what made it so noticeable for me and annoying at moments. But hey, if it only happens every now and then, I have no problem with that.

Yes that makes sense. Glad it works then.
