### ISSUE TITLE
[Feature] Hide statusline in NvimTree

### ISSUE THREAD

**Issue by siduck76** [famiu/feline.nvim#154]
NvimTree provides a highlight : NvimTreeStatuslineNC through which I can make it hidden by making its guifg/bg color same as nvimtree bg color. This worked with galaxyline but doesnt work with feline :/ 

![image](https://user-images.githubusercontent.com/59060246/136647718-3083f8d0-56c4-48ed-9494-6ec27c1cc845.png)

![image](https://user-images.githubusercontent.com/59060246/136647839-3647f306-bbca-4663-8bb4-d0cce542930a.png)

I colored that hl group to make it match nvimtree's bg color so the inactive statusline in nvimtree  (unfocused nvimtree) looks hidden. But it works for NvimTreeStatusline only but not for NvimTreeStatuslineNC

![image](https://user-images.githubusercontent.com/59060246/136647759-2e1ce3fc-4b7d-465f-8546-75d9754a4220.png)

**Comment by siduck76** [comment]
https://github.com/kyazdani42/nvim-tree.lua/issues/424#issuecomment-857388566

**Comment by famiu** [comment]
Did you try putting NvimTree on forced_inactive and making the inactive components table empty?

**Comment by famiu** [comment]
> making the inactive components as empty fixes it but I want the thin inactive statusline too
> 
> ![image](https://user-images.githubusercontent.com/59060246/137613772-1677d257-4dd9-4a98-90b0-c174e85e444e.png)

Just set `StatusLineNC` for that
