### ISSUE TITLE
Statusline jumps a little bit when switching nvim modes, because the names are of different length. How this can be eliminated?

### ISSUE THREAD

**Issue by VKondakoff** [famiu/feline.nvim#155]
Hi!

The names of the edit modes have different length and statusline jumps a little bit when switching modes.
If there is something we can do about this?

Thanks!

**Comment by melkster** [comment]
Is it possible customize the [Vi-mode indicator text](https://github.com/feline-nvim/feline.nvim/blob/e54e0cc5338b44d97dcaab83dd67d5a522656774/lua/feline/providers/vi_mode.lua#L5-L38)? For example change `BLOCK` to `V-BLOCK`, etc. I would also like to use padding but only for text that is shorter than `NORMAL` (`BLOCK`, `LINES`, etc.) to reduce jumping of the statusline while avoiding the huge padding that `NORMAL` receives if I set `opts.padding`. I figured if I would just add an extra trailing space to those words it would give me the desired effect.

**Comment by famiu** [comment]
> Is it possible customize the [Vi-mode indicator text](https://github.com/feline-nvim/feline.nvim/blob/e54e0cc5338b44d97dcaab83dd67d5a522656774/lua/feline/providers/vi_mode.lua#L5-L38)? For example change `BLOCK` to `V-BLOCK`, etc. I would also like to use padding but only for text that is shorter than `NORMAL` (`BLOCK`, `LINES`, etc.) to reduce jumping of the statusline while avoiding the huge padding that `NORMAL` receives if I set `opts.padding`. I figured if I would just add an extra trailing space to those words it would give me the desired effect.

I have no intention of implementing all that, so if you want that behavior, please make your own provider function, it shouldn't be too hard

**Comment by ram02z** [comment]
> Is it possible customize the [Vi-mode indicator text](https://github.com/feline-nvim/feline.nvim/blob/e54e0cc5338b44d97dcaab83dd67d5a522656774/lua/feline/providers/vi_mode.lua#L5-L38)? For example change `BLOCK` to `V-BLOCK`, etc. I would also like to use padding but only for text that is shorter than `NORMAL` (`BLOCK`, `LINES`, etc.) to reduce jumping of the statusline while avoiding the huge padding that `NORMAL` receives if I set `opts.padding`. I figured if I would just add an extra trailing space to those words it would give me the desired effect.

Personally, I use this as my vi-mode provider to eliminate the jumping of the statusline
```lua
provider = function()
  local mode = require("feline.providers.vi_mode").get_vim_mode()
  return " " .. mode:sub(1, 1) .. " "
end
```

However, like @famiu said, the implementation you described shouldn't be too difficult as a custom provider.

Just copy over this table https://github.com/feline-nvim/feline.nvim/blob/master/lua/feline/providers/vi_mode.lua#L5-L38 and customize the aliases to your liking. And then your final provider should look something like this:
```lua
provider = function()
  return mode_alias[vim.api.nvim_get_mode().mode]
end

**Comment by melkster** [comment]
@ram02z I did that and got exactly what I wanted, thank you :)
