### ISSUE TITLE
[Feature] Colored file icons

### ISSUE THREAD

**Issue by gokulsoumya** [famiu/feline.nvim#16]
Colored file icons would be nice to have, similar to galaxyline.

ref. This is how [galaxyline does it](https://github.com/glepnir/galaxyline.nvim/blob/cbf64bd4869c810b92f6450ed8763456c489be87/lua/galaxyline/provider_fileinfo.lua#L166-L170) .

**Comment by famiu** [comment]
Well, feline gives the filename the same highlight as the file icon, changing that would mean breaking it for everyone else using Feline. Does Feline even need colored icons by default? It's quite easy to set it up yourself.

**Comment by gokulsoumya** [comment]
Keeping backwards compatibility in mind, how about providing special component values for `file_info`, similar to `file_modified_icon` and `type` ? So something like `file_modified_icon_hl`, `filename_hl` and `fileicon_hl` for highlighing each part.

**Comment by gokulsoumya** [comment]
Looking at the source now I see that the highlight logic is separate from the component text generation itself. So using special component values would be too convoluted. I think I'll set it up in my personal config as separate components.

**Comment by famiu** [comment]
> Looking at the source now I see that the highlight logic is separate from the component text generation itself. So using special component values would be too convoluted. I think I'll set it up in my personal config as separate components.

That would be the appropriate way of doing it, yes
