### ISSUE TITLE
[Feature] Use StatusLine highlight group by default

### ISSUE THREAD

**Issue by ldelossa** [famiu/feline.nvim#164]
**Is your feature request related to a problem? Please describe.**
I like this statusbar, but themeing it is a bit intense. 

**Describe the solution you'd like**
Would it be possible to set the default bg to the "StatusLine" highlight group so it "just works" with color schemes?

**Comment by ldelossa** [comment]
I'm also noticing something like this is not possible:

```
local colors = { 
    bg = 'StatusLine',
    fg = "#e4e4e4"
}

require('feline').setup({
    colors = colors
})
```

This makes it difficult for individuals who theme switch,  as we expect StatusLine to change when the colorscheme changes.

**Comment by vladimir-popov** [comment]
I think you can't use highlight group to define fg or bg color, because hg describes both of them. But, you can use a name of hg to specify highlight of your component:
```lua
{
     provider = "my_component",
     hl = "StatusLine"
}
```

**Comment by famiu** [comment]
This has been done before but caused all sorts of other issues with highlight configuration such as the '^' character showing up in the inactive statusline due to Neovim's behavior caused by `StatusLine` and `StatusLineNC` having the same values, so it's not going to be done.

**Comment by ldelossa** [comment]
@famiu fair enough. I've worked around this by just writing some lua anyway. 

One thing I'm still struggling with is, i often switch my vim theme from light to dark. With previous status lines using HL, the line colors would change as well. 

With Feline however, if i reload the module after the appropriate variables have changed, the status line just breaks. Is there a way to reload Feline during runtime? After its first setup

**Comment by famiu** [comment]
> @famiu fair enough. I've worked around this by just writing some lua anyway.
> 
> One thing I'm still struggling with is, i often switch my vim theme from light to dark. With previous status lines using HL, the line colors would change as well.
> 
> With Feline however, if i reload the module after the appropriate variables have changed, the status line just breaks. Is there a way to reload Feline during runtime? After its first setup

What do you mean by "status line just breaks"? Are you talking about the highlights? If so, have you tried doing `require('feline').reset_highlights()`

**Comment by ldelossa** [comment]
@famiu what i mean by breaks is, i attempt to reload the entire plugin with plenary's reload method, and when i do all elements on the status line disappear. 

I haven't tried the mentioned method. I will try this.

**Comment by ldelossa** [comment]
@famiu so I attempted to call the function `require('feline').reset_highlights()` in my theme set function, and it results in a completely broken status line. 

![image](https://user-images.githubusercontent.com/5642902/143725220-79a2fb3f-fe6d-4e60-a361-667b4eb2d41c.png)


Here is the theme switch functions:

```
 vim.cmd [[
 function! DarkMode()
     let $BAT_THEME="1337"
     let $FZF_DEFAULT_OPTS='--keep-right --color="dark" --color="header:75,info:75" --bind ctrl-d:preview-page-down,ctrl-u:preview-page-up'
     colorscheme vimdark
     " needs to source in-order to set fzf-lua fzf theme again.
     source ~/.config/nvim/lua/configs/fzf.lua
     lua require('feline').reset_highlights()
 endfunction
 ]]

vim.cmd [[ 
function! LightMode()
     let $BAT_THEME="gruvbox-light"
     let $FZF_DEFAULT_OPTS='--keep-right --color="light" --color="header:25,info:25" --bind ctrl-d:preview-page-down,ctrl-u:preview-page-up'
     colorscheme vimlight
     source ~/.config/nvim/lua/configs/fzf.lua
     lua require('feline').reset_highlights()
endfunction
]]
```

My feline config looks like  this, which checks the current vim theme: 

```
local colors = {}
if vim.g.colors_name == "vimdark" then
    colors = { 
        bg = '#262626',
        fg = "#e4e4e4",
        blue = '#0087af',
        yellow = '#ffff5f',
        green = '#87af87',
        grey = '#e4e4e4'
    }
else 
    colors = { 
        fg = '#3a3a3a',
        bg = "#e4e4e4",
        blue = '#005f87',
        yellow = '#ffff5f',
        green = '#87af87',
        grey = '#4a4a4a'
    }
end
```

**Comment by famiu** [comment]
The issue seems to be that your Feline colors are not changed after reloading. You might actually want to use Feline color themes and switch to the appropriate color theme once you change the colorscheme, and then use `require('feline').reset_highlights()`

**Comment by ldelossa** [comment]
Thanks a lot. Not immediately sure what "feline color schemes" are but ill look at the docs further to find out.

**Comment by ldelossa** [comment]
@famiu what I'm failing to see is how to set/reset the default foreground and background colors. 

I can assign highlight groups to component parts, and I'm assuming if I theme switch and reset the highlights, they will switch as well. but can I assign the default foreground and background color of the bar to highlight groups? 

Also I see no mention of a "feline theme" in your docs, what are you referring to in your previous messages?

**Comment by famiu** [comment]
@ldelossa you should probably open a new issue for this since it's hard to keep track of a closed issue, I can answer your questions there
