### ISSUE TITLE
Force inactive feline in netrw and trouble plugin

### ISSUE THREAD

**Issue by imSafdarAwan** [famiu/feline.nvim#165]
**Is your feature request related to a problem? Please describe.**
i use netrw as file explorer and trobule for viewing the lsp dignostics but how can i force inactive the feline in trouble and netrew

**Comment by famiu** [comment]
What's wrong with just using the `force_inactive` table to configure Feline to be inactive on those windows?

**Comment by famiu** [comment]
Closing this issue since what you're asking for is already possible easily through the `force_inactive` table. Feel free to reopen if I misunderstood what you meant
