### ISSUE TITLE
[Feature] More Options on file_info provider

### ISSUE THREAD

**Issue by FrenzyExists** [famiu/feline.nvim#172]
**Is your feature request related to a problem? Please describe.**
TL;DR I wanted to NOT use web-devicons which appear on the left of the module, there's no option to turn it off.

**Describe the solution you'd like**
An option to turn off the left icon

**Comment by FrenzyExists** [comment]
Ok, so I took matters because I'm impatient, I made a PR where I could enable/disable the devicons on the left of the file provider, here's a preview:

![image](https://user-images.githubusercontent.com/47986470/142719878-c72e6e88-f6e3-4e26-a63e-d7e9add251bc.png)

![image](https://user-images.githubusercontent.com/47986470/142719885-430cc5c1-b50f-471c-8df1-e93077d4c7d8.png)

When set to true...

![image](https://user-images.githubusercontent.com/47986470/142719891-e2d430e4-c503-4d94-9000-f3dde610312a.png)

Anyway, gonna make a PR real quick

**Comment by FrenzyExists** [comment]
btw, yes, for some reason the bar is kinda messed due to the glyph, not sure why tho

**Comment by famiu** [comment]
you can accomplish this by setting the icon to an empy string
