### ISSUE TITLE
[Feature] Single status line at the bottom

### ISSUE THREAD

**Issue by d-miketa** [famiu/feline.nvim#175]
[Windline](https://github.com/windwp/windline.nvim) defines a single status line at the bottom of Neovim. I really like Feline’s config patterns but it’d be great if the status line could stay at the bottom rather than jump around, following the active window. 

Seems like it could need a rather substantial rewrite though.

**Comment by famiu** [comment]
Don't plan to implement it in Feline. Though I do plan to make a contribution to Neovim core that allows having a single statusline
