### ISSUE TITLE
Feline crashed

### ISSUE THREAD

**Issue by 6cdh** [Famiu/feline.nvim#2]
I don't know why, but it just blinks once and then disappears.

My config can be found [here](https://github.com/6cdh/dotfiles/blob/main/nvim/.config/nvim/lua/statusline.lua).

In fact, I just use

```lua
require'feline'.setup()
```

When I run `:checkhealth`, feline works on new buffer until `Running healthchecks...` disappears. Then feline also disappears.

**Comment by 6cdh** [comment]
```lua
print(vim.g.statusline_winid)
print(vim.fn.win_getid())
```

would output

```
nil
1000
```

**Comment by Famiu** [comment]
I can't reproduce your issue. Could you give me a minimal vimrc where this happens and then tell me the steps to reproduce?

**Comment by 6cdh** [comment]
I don't know what happened. After I removed all of my plugins and reinstall them one by one, everything works! Maybe one plugin caused the problem, but update them will solve it.

**Comment by gblock0** [comment]
I just ran into this as well. For anyone that comes across this in the future, make sure that no other statusline plugins are being loaded. I realized that I was loading another statusline plugin _after_ `feline`, so `feline` was getting overwritten.

**Comment by famiu** [comment]
> I just ran into this as well. For anyone that comes across this in the future, make sure that no other statusline plugins are being loaded. I realized that I was loading another statusline plugin _after_ `feline`, so `feline` was getting overwritten.

I'm going to add this to the Q&A section of the documentation

**Comment by collegeimprovements** [comment]
I'm also facing the same issue.

**Comment by famiu** [comment]
> I'm also facing the same issue.

Did you make sure that no other statusline plugins are installed? If you did, try using the minimal init.lua provided with feline and see if it works with the minimal init.lua
