### ISSUE TITLE
Use a function in a table of separators

### ISSUE THREAD

**Issue by pjcj** [famiu/feline.nvim#20]
Using a function in a table of separators is difficult.  As far as I can can tell it appears to be explicitly disallowed here, at least as the first element: https://github.com/famiu/feline.nvim/blob/f659ae8df487ab2107c82418a7f6038c9fb91204/lua/feline/generator.lua#L135

And it's not possible for a function to return a table of separators.

I can bodge things by having a table which has an empty string as the first element followed by functions, but this feels wrong.

Have I missed something, or is there room for improvement here?

**Comment by famiu** [comment]
It should be fixed now. If it works, please close this issue.

**Comment by pjcj** [comment]
Perfect! Thanks for the quick fix.
