### ISSUE TITLE
[Bug] nocolors

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [famiu/feline.nvim#25]
**Neovim version**
The output of `nvim --version`.
0.5 release
**Feline version**
`cd` to the directory containing Feline and use `git rev-parse HEAD`, and put the output of that here.
cfc0ecfd5e6d37e45ca5102e76cbbbc8f5a03d26

**Describe the bug**
no colors 
![image](https://user-images.githubusercontent.com/2133400/127618607-c5830c03-8c26-4df8-a47d-043fe668bb74.png)

**To Reproduce**

**Expected behavior**

**Does this error occur in the minimal init file?**
Use the following commands to download the minimal init file provided by Feline:
`curl -fLO https://raw.githubusercontent.com/famiu/feline.nvim/master/minimal_init.lua`

Modify the file to your needs (if necessary), then load Neovim using:
`nvim -u minimal_init.lua`

And check if your issue still occurs.

**Provide modified minimal_init.lua**
If you modified the minimal_init.lua that Feline provides by default in order to fit your configuration, put it here. Otherwise ignore this part.

**Screenshots**

**Additional context**
Add any other context about the problem here (eg: other plugins that may conflict with this plugin, configuration options that you think might cause the issue, etc.).

**Comment by famiu** [comment]
Does it happen if you use an older version of Feline?

**Comment by dakennguyen** [comment]
I'm having the same issue after this PR https://github.com/famiu/feline.nvim/pull/24.
![image](https://user-images.githubusercontent.com/18320285/127664909-c970aaa0-53b5-49eb-89df-569d846f770a.png)

**Comment by famiu** [comment]
Does it work now?

**Comment by dakennguyen** [comment]
It's working now for me
