### ISSUE TITLE
[Feature] Allow specific highlighting for icons

### ISSUE THREAD

**Issue by Melkster** [famiu/feline.nvim#28]
Is it possible to set a different highlighting for a component's icon?

If not I think it would be great if their highlighting were configurable just like how the separators are configured. I.e. something like this:

```lua
table.insert(components.right.active, {
  provider = 'git_branch',
  hl = { bg = 'line_bg' },
  icon = {
    str = '  '
    hi = {fg = 'orange'}
  }
})

```

**Comment by famiu** [comment]
I'm currently busy so I won't be able to work on it anytime soon. It should be an easy Pull Request to make though. So a PR would be very appreciated.

**Comment by Melkster** [comment]
I understand! I probably won't have time to work on a PR either sadly :)

**Comment by ram02z** [comment]
@Melkster Can you please test #34?

**Comment by Melkster** [comment]
Works great! That's exactly what I meant :)
