### ISSUE TITLE
[Bug] Empty statusline with default setup

### ISSUE THREAD

**Issue by Anrock** [famiu/feline.nvim#29]
**Neovim version**
```
NVIM v0.5.0-dev+1414-g8cdffd42d-dirty
Build type: Gentoo
Lua 5.1
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -mtune=native -fomit-frame-pointer -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/portage/portage/app-editors/neovim-9999/work/neovim-9999_build/config -I/home/portage/portage/app-editors/neovim-9999/work/neovim-9999/src -I/usr/include -I/home/portage/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto -I/home/portage/portage/app-editors/neovim-9999/work/neovim-9999_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Feline version**
`9977073d8f5c064785ff6b44aad30cbc6d887da0`

**Describe the bug**
Statusline is empty when using default feline theme

**To Reproduce**
Follow installation steps from readme

**Expected behavior**
Feline statusline not empty

**Does this error occur in the minimal init file?**
No.

**Provide modified minimal_init.lua**
I'm using paq instead of packer, here's minimal config when feline doesn't work
```
vim.cmd 'packadd paq-nvim'

local paq = require('paq-nvim').paq
paq 'famiu/feline.nvim'

require('feline').setup()
```

**Comment by ram02z** [comment]
Using your minimal config and I can't reproduce. I am assuming you have paq installed and ran `PaqInstall`.

**Comment by Anrock** [comment]
Any idea how can I debug this/get more info? Additional logs, debug prints, etc?

**Comment by ram02z** [comment]
> 
> 
> Any idea how can I debug this/get more info? Additional logs, debug prints, etc?

According to your neovim version, you are using a prerelease of 0.5. Try updating to 0.5 stable or the nightly and see if that fixes it. Otherwise, upload your nvim log (run `nvim -V10nvim.log`)

**Comment by Anrock** [comment]
I've checked the log and found the reason - I had galaxyline installed prior to feline and for some reason neovim still sourced galaxyline files and there was some autocommand defined that was loading galaxyline on buf enter. And plugins clashed or feline was overriden or something.
After removing galaxyline files manually (I guess PaqClean would do the trick too) - everything works fine.
