### ISSUE TITLE
[Feature request]  custom truncated the long components

### ISSUE THREAD

**Issue by MaiLunJiye** [famiu/feline.nvim#32]
**Is your feature request related to a problem? Please describe.**

Unreasonable rendering of too long components.

For example:
```lua
-- config:
local cur_function = {
    provider = function()
        return vim.fn["nvim_treesitter#statusline"](90)
    end,
    enabled = function()
        return vim.NIL ~= vim.fn["nvim_treesitter#statusline"](90)
    end,
    left_sep = ' ',
    hl = {
        fg = colors.yellow
    }
}

local components = {
    left = {
        active = {
            comps.vi_mode.left,
            comps.file.info,
            cur_function,
-- .......
        },
        inactive = {
            comps.file.info
        }
    },
-- .........
}

require'feline'.setup {
-- .....
    components = components,
-- ....
}

```

it work like that:
<img width="802" alt="截屏2021-08-20 上午10 20 11" src="https://user-images.githubusercontent.com/20548127/130169181-5e9f00b3-1ba0-4425-b60c-30369178109d.png">

but if the component too long , it work like that:
<img width="741" alt="截屏2021-08-20 上午10 31 54" src="https://user-images.githubusercontent.com/20548127/130169997-1bee84e2-db4e-4700-9a7f-a43c48b718e6.png">

`comps.vi_mode.left` ,  `comps.file.info`  was truncated.

and now i solve it by a status line mark `%<`
```
provider = function()
    return "%<" .. vim.fn["nvim_treesitter#statusline"](90)
end
```

it work like that:
<img width="698" alt="截屏2021-08-20 上午10 56 33" src="https://user-images.githubusercontent.com/20548127/130172162-815cba78-294f-4098-a856-ed863c6d8fe5.png">

However, display function name is more usefully than function signature

**Describe the solution you'd like**
A clear and concise description of what you want to happen. I hope it can truncate.

Therefore,  i hope we can cut off the tail rather than the head of component, like that :

<img width="609" alt="截屏2021-08-20 上午11 06 53" src="https://user-images.githubusercontent.com/20548127/130173056-8daaf627-cf86-4935-b438-7d8308cbe8e6.png">

**Describe alternatives you've considered**

Easy goal: cut off the tail for some component.

Future hope:
It just an idea without detail.
I hope each component can set 3  properties: `max_size`, `min_size`, `truncate_level`. For the too long component, it can truncate the low level component to min_size. 

**Additional context**

**Comment by famiu** [comment]
I mean, it's easy to just implement truncation in the provider function itself, right?

**Comment by famiu** [comment]
I'm not sure if it'll be worth implementing a functionality like this. Feline is supposed to be minimal and expects most advanced things such as truncation to be done by the user since there's no one-size-fits-all when it comes to things like this. But at the same time it seems to be a good feature to add. Others' opinions on this would be appreciated

**Comment by ram02z** [comment]
I use the following function in my config for custom providers to help me truncate or disable them. 

```lua
-- Returns true if 1/2 window width is greater than cols
local has_width_gt = function(cols, winid)
  winid = winid or 0
  return vim.api.nvim_win_get_width(winid) / 2 > cols
end
```

>
> But at the same time it seems to be a good feature to add. Others' opinions on this would be appreciated

I agree that this feature seems good to add but it can introduce a decent amount of complexity to the code, like caching might. However, there is probably an elegant solution that another statusline plugin implements.

**Comment by famiu** [comment]
> I agree that this feature seems good to add but it can introduce a decent amount of complexity to the code, like caching might.

Mhm, and it also goes against Feline's design goal of minimalism and avoiding adding too many features.

> However, there is probably an elegant solution that another statusline plugin implements.

Unless it's something very simple like a 2-3 line solution, I wouldn't be in favor of adding it personally.

**Comment by famiu** [comment]
Closing this issue as I don't intend to work on it. If someone can implement it in a very simple manner that doesn't pollute the pre-existing code, they can make a PR, but I can't guarantee it being accepted in that case either.

**Comment by famiu** [comment]
I've changed my mind regarding this. I think a very simple form of truncation can be added. I'll begin work on it soon

**Comment by famiu** [comment]
@MaiLunJiye can you please check if #65 does what you ask for

**Comment by famiu** [comment]
I've decided that at the end, truncation is something that should be implemented by the user after all. So I'm going to close this issue.

**Comment by Melkster** [comment]
@famiu I understand if you don't want to add this functionality to feline. Do you have any advice on how I could add truncation my own providers? Perhaps the README could mention a simple example of how one could do accomplish that?

**Comment by famiu** [comment]
> @famiu I understand if you don't want to add this functionality to feline. Do you have any advice on how I could add truncation my own providers? Perhaps the README could mention a simple example of how one could do accomplish that?

I'll try to work on adding docs for that soon

**Comment by famiu** [comment]
> @famiu I understand if you don't want to add this functionality to feline. Do you have any advice on how I could add truncation to my own providers? Perhaps the README could mention a simple example of how one could accomplish that?

So, what kind of truncation do you want?
