### ISSUE TITLE
Read only tag on the feline would be great 

### ISSUE THREAD

**Issue by imSafdarAwan** [famiu/feline.nvim#35]
some times we start editing a file then if we try to save it it shows read only can you add  a read only tag in feline that would be great

**Comment by ram02z** [comment]
@imSafdarAwan I just use the following snippet.
```lua
{
  provider = "",
  hl = { fg = "red" },
  right_sep = " ",
  enabled = function()
    return vim.bo.readonly
  end,
}
```

The implementation is kind of basic. You don't need `right_sep` and you can change the hl and provider values to whatever you like.

**Comment by imSafdarAwan** [comment]
> @imSafdarAwan I just use the following snippet.
> 
> ```lua
> {
>   provider = "",
>   hl = { fg = "red" },
>   right_sep = " ",
>   enabled = function()
>     return vim.bo.readonly
>   end,
> }
> ```
> 
> The implementation is kind of basic. You don't need `right_sep` and you can change the hl and provider values to whatever you like.

hey that was very helpful but can i show the ale dignostics in the feline

**Comment by imSafdarAwan** [comment]
they provide this function i am new to the nvim so i don't know any of the vimL or lua i can't work it out with 
the feline

function! LinterStatus() abort
    let l:counts = ale#statusline#Count(bufnr(''))

    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors

    return l:counts.total == 0 ? 'OK' : printf(
    \   '%dW %dE',
    \   all_non_errors,
    \   all_errors
    \)
endfunction

set statusline=%{LinterStatus()}

**Comment by famiu** [comment]
I'm going to reopen the issue and keep it open until I add a read-only section for feline's file info
