### ISSUE TITLE
[Bug] Highlight group 'Normal' has no background highlight.

### ISSUE THREAD

**Issue by AllenDang** [famiu/feline.nvim#37]
With newest version from master branch, I got following error message.
```
Highlight group 'Normal' has no background highlight.

Please provide an RGB hex value or highlight group with a background value for 'background_colour' option

Defaulting to #000000
```

**Comment by famiu** [comment]
What's the last commit that works for you? Also, did you try the minimal config?

**Comment by AllenDang** [comment]
@famiu I have to set every bg of hl manually to get rid of the error message.

**Comment by famiu** [comment]
> @famiu I have to set every bg of hl manually to get rid of the error message.

You haven't answered my question. Does the minimal init.lua work for you? Did Feline work for you in the past and an update broke it or was it broken since you started using it?

**Comment by AllenDang** [comment]
Feline works for me in past, I mean yesterday. This error message occurred today after update. It still there even with minimal init.lua. I'm not quite sure it is related to feline, since today has lots of package were updated.

**Comment by famiu** [comment]
> Feline works for me in past, I mean yesterday. This error message occurred today after update. It still there even with minimal init.lua. I'm not quite sure it is related to feline, since today has lots of package were updated.

Can you try the previous commits and tell me what's the last commit that still works for you?

**Comment by AllenDang** [comment]
@famiu `6fd862ecd5232c59647949c836b2f7f4409ef3d1` works for me.

**Comment by ram02z** [comment]
That is strange, my PR didn't change how highlight groups are parsed.

**Comment by famiu** [comment]
> @famiu `6fd862ecd5232c59647949c836b2f7f4409ef3d1` works for me.

Can you do `nvim --version` in a command line and post the output of it here?

**Comment by AllenDang** [comment]
@famiu Sure.
```sh
NVIM v0.6.0-dev+1680-g9695691ee
Build type: Release
LuaJIT 2.1.0-beta3
编译者 allendang@MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/HEAD-9695691/share/nvim"

Run :checkhealth for more info
```

**Comment by famiu** [comment]
> @famiu Sure.
> 
> ```shell
> NVIM v0.6.0-dev+1680-g9695691ee
> Build type: Release
> LuaJIT 2.1.0-beta3
> 编译者 allendang@MacBook-Pro.local
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>      系统 vimrc 文件: "$VIM/sysinit.vim"
>          $VIM 预设值: "/usr/local/Cellar/neovim/HEAD-9695691/share/nvim"
> 
> Run :checkhealth for more info
> ```

Hmm... I'm wondering if this is an Neovim 0.6 thing. If possible, could you try using it in Neovim 0.5 and see if it works?

**Comment by ram02z** [comment]
@AllenDang It might be a colorscheme issue. Does the same error message occur for another highlight group?

**Comment by AllenDang** [comment]
@famiu I think it should related to nvim 0.6. I tried several commits with neovim 0.5, both of them works fine.
One more thing, can I disable the color file type icon for FileInfo? It looks very weired.
![截屏2021-09-01 上午11 40 28](https://user-images.githubusercontent.com/18550/131608049-ade2d2e7-8225-4c97-8d3b-16cc7be80b7b.png)

**Comment by famiu** [comment]
> One more thing, can I disable the color file type icon for FileInfo? It looks very weired.
That was just fixed. Update Feline and try again.

**Comment by famiu** [comment]
> I think it should related to nvim 0.6. I tried several commits with neovim 0.5, both of them works fine.

Strange indeed. I don't know what changes nvim 0.6 has. @ram02z any ideas?

**Comment by ram02z** [comment]
> 
> Strange indeed. I don't know what changes nvim 0.6 has. @ram02z any ideas?

I am using nvim-nightly and I am not running into any errors, which like I said prior, might mean it is a colorscheme issue. @AllenDang Are you using a custom config for feline? If so, can you upload to a github gist or similar?

**Comment by famiu** [comment]
> > Strange indeed. I don't know what changes nvim 0.6 has. @ram02z any ideas?
> 
> I am using nvim-nightly and I am not running into any errors, which like I said prior, might mean it is a colorscheme issue. @AllenDang Are you using a custom config for feline? If so, can you upload to a github gist or similar?

But the fact that they can reproduce it even with the minimal init implies that it's not a colorscheme issue... unless plugins are still being loaded.

@AllenDang Can you try the minimal init again, but this time do `nvim --noplugin -u minimal_init.lua` instead and see if it works or not

**Comment by AllenDang** [comment]
`nvim --noplugin -u minimal_init.lua ` works with no issue.

**Comment by famiu** [comment]
> `nvim --noplugin -u minimal_init.lua ` works with no issue.

@AllenDang So it is in fact either an issue with your colorscheme or another plugin is interfering with Feline. Try using a different colorscheme or removing plugins you think might be the cause
