### ISSUE TITLE
[Feature] Whitespace provider

### ISSUE THREAD

**Issue by SmiteshP** [famiu/feline.nvim#47]
It would be great to have a whitespace provider like in [galaxyline](https://github.com/glepnir/galaxyline.nvim/blob/d544cb9d0b56f6ef271db3b4c3cf19ef665940d5/lua/galaxyline/provider_whitespace.lua)
It is a very useful feature and I feel its complex enough for it be included as a provider.

**Comment by famiu** [comment]
what do you mean by whitespace provider?

**Comment by SmiteshP** [comment]
> what do you mean by whitespace provider?

It shows information about if there is any trailing whitespace or inconsistent indentation styles etc.

**Comment by SmiteshP** [comment]
For example

![Screenshot from 2021-09-03 17-24-04](https://user-images.githubusercontent.com/43147494/132001378-1c52045b-afd6-48dc-a4a5-e6df376f42a6.png)

**Comment by famiu** [comment]
I don't think it's a necessary feature personally. Also, I'd really like to avoid feature-bloat with Feline since that goes against its design goal of minimalism and only providing the bare minimum.

**Comment by stumash** [comment]
so, I'm okay with this not being included in feline, but I also really want this feature - I hate trailing whitespace and mixed-indent in my files, and I want my statusbar to tell me when they're present.

is there some kind of plugin architecture? can I make my own plugin and have feline use it as a provider?

**Comment by famiu** [comment]
> so, I'm okay with this not being included in feline, but I also really want this feature - I hate trailing whitespace and mixed-indent in my files, and I want my statusbar to tell me when they're present.
> 
> is there some kind of plugin architecture? can I make my own plugin and have feline use it as a provider?

Just check the code for galaxyline's whitespace provider (in the link that the issue creator shared above)

**Comment by stumash** [comment]
@famiu I'm making a neovim plugin that makes these easy to do. I'll post here with a link in the next few days

**Comment by stumash** [comment]
https://github.com/stumash/snowball.nvim
