### ISSUE TITLE
Config showcase

### ISSUE THREAD

**Issue by famiu** [famiu/feline.nvim#5]
I was thinking that it'd be nice to have a config showcase section in the README like galaxyline does. So it would be nice if people could post their own configs and screenshots of their statusline in this thread

**Comment by crivotz** [comment]
![normal](https://user-images.githubusercontent.com/3275600/114735062-1ecd3000-9d45-11eb-95da-281a2d9bdaf5.png)
![insert](https://user-images.githubusercontent.com/3275600/114735072-1ffe5d00-9d45-11eb-81a8-a666e5f0fa94.png)
![view](https://user-images.githubusercontent.com/3275600/114735084-21c82080-9d45-11eb-872a-376498d57a3c.png)

Config [here](https://github.com/crivotz/nv-ide/blob/master/lua/plugins/feline.lua)

**Comment by Famiu** [comment]
> Normal mode
> ![normal](https://user-images.githubusercontent.com/3275600/114735062-1ecd3000-9d45-11eb-95da-281a2d9bdaf5.png)
> Insert mode
> ![insert](https://user-images.githubusercontent.com/3275600/114735072-1ffe5d00-9d45-11eb-81a8-a666e5f0fa94.png)
> Visual mode
> ![view](https://user-images.githubusercontent.com/3275600/114735084-21c82080-9d45-11eb-872a-376498d57a3c.png)
> 
> Config [here](https://github.com/crivotz/nv-ide/blob/master/lua/plugins/feline.lua)

Thanks, added it to the screenshots section

**Comment by 6cdh** [comment]
![Screenshot from 2021-04-15 16-20-16](https://user-images.githubusercontent.com/39000776/114838041-e68e2600-9e06-11eb-9334-431a627ff144.png)

[Config](https://github.com/6cdh/dotfiles/blob/main/nvim/.config/nvim/lua/statusline.lua)

**Comment by Famiu** [comment]
> ![Screenshot from 2021-04-15 16-20-16](https://user-images.githubusercontent.com/39000776/114838041-e68e2600-9e06-11eb-9334-431a627ff144.png)
> 
> [Config](https://github.com/6cdh/dotfiles/blob/main/nvim/.config/nvim/lua/statusline.lua)

I also just added a default `lsp_client_names` provider by the way, so you don't have to make your own anymore

**Comment by 6cdh** [comment]
@famiu Thanks, just clear it.

**Comment by luizcoro2** [comment]
![2021-04-19-23:07 19](https://user-images.githubusercontent.com/70335871/115327167-dd81b980-a164-11eb-9c02-7a3a1b6a94b5.png)

[Config](https://bitbucket.org/luizcoro/dotfiles/src/master/.config/nvim/lua/plugins/feline.lua)

**Comment by famiu** [comment]
> ![2021-04-19-23:07 19](https://user-images.githubusercontent.com/70335871/115327167-dd81b980-a164-11eb-9c02-7a3a1b6a94b5.png)
> 
> [Config](https://bitbucket.org/luizcoro/dotfiles/src/master/.config/nvim/lua/plugins/feline.lua)

It's been added. By the way, Feline allows you to define your own color overrides so you don't have to use variables like that.

**Comment by luizcoro2** [comment]
> > ![2021-04-19-23:07 19](https://user-images.githubusercontent.com/70335871/115327167-dd81b980-a164-11eb-9c02-7a3a1b6a94b5.png)
> > [Config](https://bitbucket.org/luizcoro/dotfiles/src/master/.config/nvim/lua/plugins/feline.lua)
> 
> It's been added. By the way, Feline allows you to define your own color overrides so you don't have to use variables like that.

Thanks! (I have updated my config)

**Comment by rafamadriz** [comment]
Here's mine with two different styles and colorschemes: 

[config](https://github.com/rafamadriz/dotfiles/tree/main/.config/nvim/lua/plugins/statusline)
## [Classic](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/classic.lua)
#### Gruvbox
![2021-Apr-25_1](https://user-images.githubusercontent.com/67771985/116002735-a7bc5500-a5ea-11eb-82e3-86d1837902cf.png)
#### Nord
![2021-Apr-25_2](https://user-images.githubusercontent.com/67771985/116002779-d3d7d600-a5ea-11eb-8772-7cb85d7bc324.png)
## [Slant](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/slant.lua)
#### Gruvbox
![2021-Apr-25](https://user-images.githubusercontent.com/67771985/116002799-e94d0000-a5ea-11eb-9472-da0d75bbcceb.png)
#### Nord
![2021-Apr-25_3](https://user-images.githubusercontent.com/67771985/116002808-efdb7780-a5ea-11eb-97eb-caf7875e9a3d.png)

**Comment by famiu** [comment]
> Here's mine with two different styles and colorschemes:
> 
> [config](https://github.com/rafamadriz/dotfiles/tree/main/.config/nvim/lua/plugins/statusline)
> ## [Classic](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/classic.lua)
> #### Gruvbox
> 
> ![2021-Apr-25_1](https://user-images.githubusercontent.com/67771985/116002735-a7bc5500-a5ea-11eb-82e3-86d1837902cf.png)
> #### Nord
> 
> ![2021-Apr-25_2](https://user-images.githubusercontent.com/67771985/116002779-d3d7d600-a5ea-11eb-8772-7cb85d7bc324.png)
> ## [Slant](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/slant.lua)
> #### Gruvbox
> 
> ![2021-Apr-25](https://user-images.githubusercontent.com/67771985/116002799-e94d0000-a5ea-11eb-9472-da0d75bbcceb.png)
> #### Nord
> 
> ![2021-Apr-25_3](https://user-images.githubusercontent.com/67771985/116002808-efdb7780-a5ea-11eb-97eb-caf7875e9a3d.png)

Thanks for your contribution, they have been added to the README

**Comment by rafamadriz** [comment]
Made another statusline inspired in vscode. [config](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/vscode.lua)
![2021-May-10](https://user-images.githubusercontent.com/67771985/117713773-9d42b380-b1c5-11eb-8a8b-76949c9b2db1.png)

**Comment by pianocomposer321** [comment]
Here's mine:
![status_line png](https://user-images.githubusercontent.com/54072354/117869424-65d51500-b260-11eb-898c-0a0b987a6275.png)

I started with @6cdh's, then changed out the colors and a few other things like the full mode indicator to make it look more like what I was used to from airline, lightline, lualine, etc.

[config](https://gist.github.com/pianocomposer321/6151c458132a97590d21415db67361a6)

**Comment by famiu** [comment]
I'm closing this. From now on, in order to add a config to the README, please make a pull request.

**Comment by pianocomposer321** [comment]
@famiu just as a side note, I think the way that lualine does this is it has a separate .md file specifically for screenshots. If too many more people want to add their config, that might be a better way to handle so the README doesn't get too cluttered.

**Comment by famiu** [comment]
> @famiu just as a side note, I think the way that lualine does this is it has a separate .md file specifically for screenshots. If too many more people want to add their config, that might be a better way to handle so the README doesn't get too cluttered.

Yup, I thought of that, don't worry

**Comment by olimorris** [comment]
I wondered if anyone has any good examples of having Feline change colors when they change their color scheme? It seems to just lose all coloring when I apply a change of theme:

![Screen Shot 2021-08-15 at 23 10 45](https://user-images.githubusercontent.com/9512444/129494237-45175142-c7eb-4bc9-a461-18a2d0b46b1e.gif)

**Comment by VKondakoff** [comment]
> > > [Config](https://bitbucket.org/luizcoro/dotfiles/src/master/.config/nvim/lua/plugins/feline.lua)
> Thanks! (I have updated my config)

Hey, can you, please, reupload your config (looks like it disappears from the previous location)?
And an additional question: what was the colorscheme you were using on this screenshot? 
Thanks! 🙏

**Comment by crivotz** [comment]
[Here my config](https://github.com/crivotz/nv-ide/blob/master/lua/plugins/feline.lua)

The colorscheme is [gruvnbox material](https://github.com/sainnhe/gruvbox-material)

**Comment by tudor07** [comment]
@luizcoro2 can you re-upload? your link does not work

**Comment by askfiy** [comment]
> Made another statusline inspired in vscode. [config](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/vscode.lua) ![2021-May-10](https://user-images.githubusercontent.com/67771985/117713773-9d42b380-b1c5-11eb-8a8b-76949c9b2db1.png)

I like it, but unfortunately I can't find the link to it.

**Comment by vycoder** [comment]
> Here's mine with two different styles and colorschemes:
> 
> [config](https://github.com/rafamadriz/dotfiles/tree/main/.config/nvim/lua/plugins/statusline)
> 
> ## [Classic](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/classic.lua)
> #### Gruvbox
> ![2021-Apr-25_1](https://user-images.githubusercontent.com/67771985/116002735-a7bc5500-a5ea-11eb-82e3-86d1837902cf.png)
> 
> #### Nord
> ![2021-Apr-25_2](https://user-images.githubusercontent.com/67771985/116002779-d3d7d600-a5ea-11eb-8772-7cb85d7bc324.png)
> 
> ## [Slant](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/slant.lua)
> #### Gruvbox
> ![2021-Apr-25](https://user-images.githubusercontent.com/67771985/116002799-e94d0000-a5ea-11eb-9472-da0d75bbcceb.png)
> 
> #### Nord
> ![2021-Apr-25_3](https://user-images.githubusercontent.com/67771985/116002808-efdb7780-a5ea-11eb-97eb-caf7875e9a3d.png)

The link for the Nord one is now dead? Does anybody know where I can find it?

**Comment by ziranjameshe** [comment]
> 

Hi, any chance you can share the config for these status lines again please? The link is gone.

**Comment by ziranjameshe** [comment]
> Here's mine with two different styles and colorschemes:
> 
> [config](https://github.com/rafamadriz/dotfiles/tree/main/.config/nvim/lua/plugins/statusline)
> 
> ## [Classic](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/classic.lua)
> #### Gruvbox
> ![2021-Apr-25_1](https://user-images.githubusercontent.com/67771985/116002735-a7bc5500-a5ea-11eb-82e3-86d1837902cf.png)
> 
> #### Nord
> ![2021-Apr-25_2](https://user-images.githubusercontent.com/67771985/116002779-d3d7d600-a5ea-11eb-8772-7cb85d7bc324.png)
> 
> ## [Slant](https://github.com/rafamadriz/dotfiles/blob/main/.config/nvim/lua/plugins/statusline/styles/slant.lua)
> #### Gruvbox
> ![2021-Apr-25](https://user-images.githubusercontent.com/67771985/116002799-e94d0000-a5ea-11eb-9472-da0d75bbcceb.png)
> 
> #### Nord
> ![2021-Apr-25_3](https://user-images.githubusercontent.com/67771985/116002808-efdb7780-a5ea-11eb-97eb-caf7875e9a3d.png)

> 

Hi @rafamadriz, any chance you can share the config for these status lines again please? The link is gone.
