### ISSUE TITLE
[Bug] statusline is updated only in current window

### ISSUE THREAD

**Issue by xeluxee** [famiu/feline.nvim#52]
**Neovim version**
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5

**Feline version**
8c809b2416fa6773719f3c391eb7b124d67c866e (latest as of now)

**Describe the bug**
Statusline is updated only in current window, so inactive statusline isn't updated. This is a problem because in the inactive part i put the window number (return value of `vim.fn.winnr()`) to make easier to jump between windows with a keybinding (space+number). When deleting a window, for example, window numbers aren't updated, making navigation between windows difficult.

**To Reproduce**
1. Vertical split (`<C-w>v`)
2. Vertical split (`<C-w>v`)
3. Go to first window (`<C-w>w`)
4. Delete it (`<C-w>c`)
5. The window on the right shows number 3, even if it is window 2.

If you jump to window 2 and come back to window 1 you'll see the number updated.

**Expected behavior**
Inactive windows should be updated.

**Screenshots**
After step 3:
![st1](https://user-images.githubusercontent.com/88047141/132313377-bb138dd0-1264-4459-a4a8-da4effbf4d21.png)

After step 4:
![st2](https://user-images.githubusercontent.com/88047141/132313468-665f78fc-9664-4c95-a013-36ea872bc379.png)

**Comment by ram02z** [comment]
I am able to to reproduce without having to delete:
1. Open a file
2. Vertical split x2

![image](https://user-images.githubusercontent.com/59267627/132337774-4fd89f37-0df6-4750-af18-5faecf47b841.png)

**Comment by xeluxee** [comment]
> I am able to to reproduce without having to delete:
> 
>     1. Open a file
> 
>     2. Vertical split x2
> 
> 
> ![image](https://user-images.githubusercontent.com/59267627/132337774-4fd89f37-0df6-4750-af18-5faecf47b841.png)

@ram02z I don't think we're talking about the same thing, my problem is about inactive windows components not being updated after leaving that window.
I don't understand what's wrong in your picture...

**Comment by ram02z** [comment]
> 
> @ram02z I don't think we're talking about the same thing, my problem is about inactive windows components not being updated after leaving that window.
> I don't understand what's wrong in your picture...

It is the same issue. Notice how the middle and right split show LUA2. The rightmost split should show LUA3. Sorry, I should have made it more clear.

**Comment by xeluxee** [comment]
Sorry i didn't understand that the number after `LUA` was the window number

**Comment by famiu** [comment]
I'm wondering what I can do in order to fix that. I could iterate through every window while generating statusline but that seems horribly ineffecient. Any ideas would be appreciated

**Comment by xeluxee** [comment]
I noticed that [lightline](https://github.com/itchyny/lightline.vim) doesn't have this problem.
Maybe an update could be triggered after window layout is changed, but I don't know if there is a way to detect a change in window layout...

**Comment by ram02z** [comment]
@famiu lightline does iterate through every window.
See https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline.vim#L23-L25

**Comment by famiu** [comment]
Check the PR I just made and see if it fixes the issue for you
