### ISSUE TITLE
[Bug] Git diff changed icon

### ISSUE THREAD

**Issue by d-miketa** [famiu/feline.nvim#57]
Hey, thanks for the great statusline plugin!

I noticed that the `git_diff_changed` icon is of a completely different style compared to the others. Here's a screenshot using the minimal init (thank you for that one btw, extremely handy):
<img width="214" alt="image" src="https://user-images.githubusercontent.com/320321/132557818-7eb504aa-ad1f-4e4f-bad7-beefb19617ee.png">
It's the exact same icon I see over at https://github.com/famiu/feline.nvim/blob/fbd31ae501a66fe1241c11f890f1deb298f7b2a5/lua/feline/providers/git.lua#L51 .

I use Fira Code Retina in Neovim v0.6.0-dev+1689-gdce50312e.

**Comment by famiu** [comment]
Do you have Nerd Fonts?

**Comment by d-miketa** [comment]
Yes, but incorrectly set up – fixed and apologies!
