### ISSUE TITLE
[Bug] Unable to port 6cdh's componenets to new components; empty statusline

### ISSUE THREAD

**Issue by MonAaraj** [famiu/feline.nvim#59]
**Neovim version**
NVIM v0.6.0-dev+221-g47f99d664
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/mon/.local/cache/paru/clone/neovim-git/src/build/config -I/home/mon/.local/cache/paru/clone/neovim-git/src/neovim-git/src -I/usr/include -I/home/mon/.local/cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/mon/.local/cache/paru/clone/neovim-git/src/build/include
Compiled by mon@artix-pc

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Feline version**
3278e3f3165b337b9213411ddb15f95ff8389274

**Describe the bug**
After trying one of the configurations given in the README.md, I get a warning message relating to the deprecated component style. It seemed simple enough to implement, so I simply replaced
```lua
local components = {
    left = {
        active = {
            comps.vi_mode.left,
            comps.file.info,
            comps.lsp.name,
            comps.diagnos.err,
            comps.diagnos.warn,
            comps.diagnos.hint,
            comps.diagnos.info
        },
        inactive = {
            comps.vi_mode.left,
            comps.file.info
        }
    },
    mid = {
        active = {},
        inactive = {}
    },
    right = {
        active = {
            comps.git.add,
            comps.git.change,
            comps.git.remove,
            comps.file.os,
            comps.git.branch,
            comps.line_percentage,
            comps.scroll_bar,
            comps.vi_mode.right
        },
        inactive = {}
    }
}
```
with:
```
local components = {
    active = {
        left = {
            comps.vi_mode.left,
            comps.file.info,
            comps.lsp.name,
            comps.diagnos.err,
            comps.diagnos.warn,
            comps.diagnos.hint,
            comps.diagnos.info
        },
        right = {
            comps.git.add,
            comps.git.change,
            comps.git.remove,
            comps.file.os,
            comps.git.branch,
            comps.line_percentage,
            comps.scroll_bar,
            comps.vi_mode.right
        }
    },
    inactive = {
        left = {
            comps.vi_mode.left,
            comps.file.info
        },
    }
}
```

Yet... Nothing was displaying on the status bar, it was simply just a bar of a solid color.

**Expected behavior**
The exact same bar, except I wouldn't get the warning. 

**Does this error occur in the minimal init file?**
Yes.

**Provide modified minimal_init.lua**
https://termbin.com/6lx2

**Screenshots**
https://imgur.com/a/olG43Jy

**Comment by famiu** [comment]
Read the README properly. Your setup is incorrect. There is no left, right or mid anymore. Feline allows a variable amount of component sections now. So you just have to do:

```lua
local components = {
    active = {
        {
            comps.vi_mode.left,
            comps.file.info,
            comps.lsp.name,
            comps.diagnos.err,
            comps.diagnos.warn,
            comps.diagnos.hint,
            comps.diagnos.info
        },
        {
            comps.git.add,
            comps.git.change,
            comps.git.remove,
            comps.file.os,
            comps.git.branch,
            comps.line_percentage,
            comps.scroll_bar,
            comps.vi_mode.right
        }
    },
    inactive = {
        {
            comps.vi_mode.left,
            comps.file.info
        },
    }
}

```

**Comment by MonAaraj** [comment]
Ah, thank you very much! And I'm really sorry for not seeing it correctly. Have a good day!
