### ISSUE TITLE
file_info providers are the same across multiple windows

### ISSUE THREAD

**Issue by 6cdh** [Famiu/feline.nvim#6]
As this image

![Screenshot from 2021-04-15 00-21-17](https://user-images.githubusercontent.com/39000776/114744725-953b5380-9d80-11eb-88a9-64b213b58545.png)

The left window is [nvim tree](https://github.com/kyazdani42/nvim-tree.lua), right is `init.lua`. But they get the same `file_info`.

I expect the left status line is

![Screenshot from 2021-04-15 00-12-44](https://user-images.githubusercontent.com/39000776/114743564-62dd2680-9d7f-11eb-9948-c75e5d8c03c4.png)

My config can be found [here](https://github.com/6cdh/dotfiles/blob/main/nvim/.config/nvim/lua/statusline.lua).

The default config get this:

![Screenshot from 2021-04-15 00-18-34](https://user-images.githubusercontent.com/39000776/114744348-2e1d9f00-9d80-11eb-99fe-c03b865a2111.png)

It's also wired.

**Comment by Famiu** [comment]
The issue seems to have been caused by an issue with `vim.wo`, it should be fixed now

**Comment by 6cdh** [comment]
Yes, Fixed. Thanks.
