### ISSUE TITLE
[Bug] got error executing when using visual on vim

### ISSUE THREAD

**Issue by rjl18nv** [famiu/feline.nvim#61]
**Describe the bug**
When i press v to use visual feature on vim it show the errors like this. Don't know could you guys help me to fix that

**Screenshots**
![Screen Shot 2021-09-11 at 17 46 33](https://user-images.githubusercontent.com/40130936/132945245-b198ca57-cba0-4480-81e8-31c27e26c9a5.png)

**Comment by famiu** [comment]
What version of Feline are you using? If it's an old version, is it still broken on the latest version?

Could you post a link to your config?

Can you reproduce the issue with the minimal config? (run using `nvim --noplugin -u /path/to/feline/minimal_init.lua`)

**Comment by famiu** [comment]
the latest commit should fix your issues

**Comment by rjl18nv** [comment]
yeah let's me try to update version again

**Comment by rjl18nv** [comment]
here is my configuration file link
https://github.com/rjl18nv/dotfiles/blob/master/nvim/lua/plugins/statusline.lua

**Comment by ram02z** [comment]
@rjl18nv add `LINES` to your `vi_mode_text` and `vi_mode_colors` tables. See this commit for more info, https://github.com/famiu/feline.nvim/commit/92d9b1a99227c4da6d4c4fa8f12b80c78f16feb2.

**Comment by rjl18nv** [comment]
let's me try thanks so much @ram02z

**Comment by rjl18nv** [comment]
it has been fixed thanks so much guys  👍
