### ISSUE TITLE
[Bug] Feline occasionally shows inactive statusline on active window

### ISSUE THREAD

**Issue by famiu** [famiu/feline.nvim#63]
Feline seems to occasionally show the inactive statusline on the active window. It seems to happen randomly and I didn't find a pattern to it yet, but it only happens when I switch tabs through mouseclick using [barbar.nvim](https://github.com/romgrk/barbar.nvim). Need to find the cause of this.

**Comment by ram02z** [comment]
> 
> 
> Feline seems to occasionally show the inactive statusline on the active window. It seems to happen randomly and I didn't find a pattern to it yet, but it only happens when I switch tabs through mouseclick using [barbar.nvim](https://github.com/romgrk/barbar.nvim). Need to find the cause of this.

It occurs due the use of `vim.schedule` in `update_inactive_windows`.
