### ISSUE TITLE
how show python virtual environment and lsp status on feline?

### ISSUE THREAD

**Issue by shaeinst** [famiu/feline.nvim#66]
i want to show python virtual environment on feline (if virtual env is activated).
also is there any way to show lsp's status?

**Comment by ram02z** [comment]
> 
> 
> also is there any way to show lsp's status?

If you want to show attached LSP client(s), you could use the `lsp_client_names` provider. There are also more providers for diagnostics, take a look at this file if you are interested: https://github.com/famiu/feline.nvim/blob/master/lua/feline/providers/lsp.lua

**Comment by shaeinst** [comment]
No, that's not what  i want. i want to show status of LSP (like it's loading)
i want following
```lua
local lsp_status = require('lsp-status')
lsp_status.register_progress()
lsp.status

```

**Comment by ram02z** [comment]
Feline doesn't use any external plugins for the lsp providers. Of course you are are free to create a provider using `lsp-status` for your config. If you can enable/disable the component, by using the `is_lsp_attached` function from the lsp provider.

**Comment by shaeinst** [comment]
great, i got status by creating custom provider. 
incase anybody need it, here is the provider
```lua
      provider = function ()
          local lsp_status = require('lsp-status')
          lsp_status.register_progress()
          return lsp_status.status()
      end

```


and how about python virtual environment? i don't know how to write provider for it. can you please write it?

**Comment by famiu** [comment]
> great, i got status by creating custom provider.
> incase anybody need it, here is the provider
> 
> ```lua
>       provider = function ()
>           local lsp_status = require('lsp-status')
>           lsp_status.register_progress()
>           return lsp_status.status()
>       end
> ```

I'd recommend moving the `local lsp_status = require('lsp-status')` to the top of the file so it doesn't get redefined everytime.

> and how about python virtual environment? i don't know how to write provider for it. can you please write it?

This should work:
```lua
provider = function() return os.getenv('VIRTUAL_ENV') end,
enabled = function() return os.getenv('VIRTUAL_ENV') ~= nil end
```

**Comment by shaeinst** [comment]
thanks.
> I'd recommend moving the local lsp_status = require('lsp-status') to the top of the file so it doesn't get redefined everytime.

this show the full location of directory instead of just name. and i don't know how to split string and select last one. in python i could do
 ```python
os.getenv('VIRTUAL_ENV').split("/")[-1] 
```
to select just the name.. how to do this in lua
>``` lua
>provider = function() return os.getenv('VIRTUAL_ENV') end,
>enabled = function() return os.getenv('VIRTUAL_ENV') ~= nil end
>```

**Comment by shaeinst** [comment]
after spending some time i found it on my own, in case someone need it, here the the custom provider for python virtual environment
```lua
    {
        provider = function()
            local name_with_path = os.getenv('VIRTUAL_ENV')
            local venv = {};
            for match in (name_with_path.."/"):gmatch("(.-)".."/") do
                table.insert(venv, match);
            end
            return venv[#venv]
        end,
        enabled = function() return os.getenv('VIRTUAL_ENV') ~= nil end
    },

```
