### ISSUE TITLE
[Bug] Inactive statuslines use current buffer for buffer options

### ISSUE THREAD

**Issue by Iron-E** [famiu/feline.nvim#69]
**Neovim version**
NVIM v0.6.0-dev+262-g643cb8a6e

**Feline version**
0506b42b11e9ef6c5c9a3710cb29f8829b33aaa8

**Describe the bug**
It appears that all inactive statuslines use the current buffer for buffer options. For example, if there is one 'Lua' buffer and another 'Rust' buffer, and you are showing the `vim.bo.ft` in the inactive statusline, it will show whichever file you are currently in on the inactive statusline rather than the inactive buffer's filetype.

**To Reproduce**

1. Use the following config:
	```lua
	require('feline').setup(
	{
		components =
		{
			active =
			{
				-- Left
				{},

				-- Middle
				{},

				-- Right
				{},
			},

			inactive =
			{
				-- Left
				{},

				-- Right
				{{provider = function() return vim.bo.ft end}},
			},
		},

		force_inactive =
		{
			bufnames = {},
			buftypes = {'help', 'prompt', 'terminal'},
			filetypes =
			{
				'dbui',
				'diff',
				'help',
				'NvimTree',
				'packer',
				'peekaboo',
				'qf',
				'undotree',
				'vista',
				'vista_markdown',
			},
		},
	})
	```
2. Open a `foo.lua` file, then open `foo.rs` in a new split.
3. Observe `foo.lua` shows "rust" when in the Rust file, and the Rust file shows "Lua" when in the Lua file.

**Expected behavior**
Use each inactive buffer separately as reference point for `vim.bo` when generating status line.

**Does this error occur in the minimal init file?**
No, because the minimal file doesn't have a config scheme like this.

**Provide modified minimal_init.lua**
All that is needed is the minimal `feline` setup command provided above.

**Screenshots**
![cap](https://user-images.githubusercontent.com/36409591/133004703-a5145dcf-6d32-40d3-8df6-c635dbdd21cf.png)
![cap](https://user-images.githubusercontent.com/36409591/133004713-c0f7d4a0-c074-4c4e-94c7-39a12ef598d7.png)

* Notice that the `NvimTree` buffer also is affected by the inactive statusline issue.

**Comment by ram02z** [comment]
Can you also reproduce when using the inbuilt `file_type` provider?

**Comment by Iron-E** [comment]
Yep, adding the `winid` param makes it work. I totally missed that in the docs. Thank you!
