### ISSUE TITLE
[Feature] Named components?

### ISSUE THREAD

**Issue by famiu** [famiu/feline.nvim#75]
I was thinking of adding named components to Feline's. So basically, components could have an extra `name` value, which could be used to access them directly from the components table without having to remember their index. It'd also help prevent code duplication in the plugin since `noicons` preset is basically the `default` preset with a few changes, we'd be able to just directly use the `default` preset and make a few modifications to it using the component names to prevent code duplication. It'd also allow people to easily modify components without having to remember the index.

The problem is, I haven't found a single way to implement them that isn't horribly ineffecient (eg: something that doesn't involve searching every component whenever a name is used for access). I tried caching the names and using metatables for access but even then it isn't foolproof since `newindex` only works for values that already don't exist, and using a proxy table prevents the table from being iterated using `ipairs`, which is something that the statusline generator needs to do. Thoughts on it would be appreciated.

**Comment by rktjmp** [comment]
Without fully knowing the problem (or maybe just to rubber duck), why can't you just have a regular table that you insert `components[component.name] = component` when setup is called? Then just treat it as a hash table?

**Comment by famiu** [comment]
> Without fully knowing the problem (or maybe just to rubber duck), why can't you just have a regular table that you insert `components[component.name] = component` when setup is called? Then just treat it as a hash table?

Because we need to have an order in which the components are placed, which can't be done with non-numerical indices
