### ISSUE TITLE
[Bug] nvim-web-devicons is not optional

### ISSUE THREAD

**Issue by Olical** [famiu/feline.nvim#77]
**Neovim version**

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/920i9s2jc9nvm8zqp8f214apf9wbm34p-neovim-unwrapped-0.5.0/share/nvim
"

Run :checkhealth for more info
```

**Feline version**

`v0.1`

**Describe the bug**

The plugin can not be initialised and used unless you have `nvim-web-devicons` installed since this commit https://github.com/famiu/feline.nvim/commit/6961f91d167a8d5e21e8388c53e94bee955d3a3b

I beleive the correct course of action is to gate that code to ensure it doesn't execute unless the module is require-able.

**To Reproduce**
 
Install feline and open Neovim without `nvim-web-devicons` installed.

**Comment by famiu** [comment]
Already fixed in latest develop

**Comment by Olical** [comment]
So fast! Sorry I didn't check for that before opening an issue, my bad. If
you're not planning on merging develop for a little while it might be worth
leaving this issue open for visibility too. It's what I do on my plugins :)
I only close once the fix is merged and released.

Thanks for the plugin! Have a good weekend!

**Comment by famiu** [comment]
> So fast! Sorry I didn't check for that before opening an issue, my bad. If you're not planning on merging develop for a little while it might be worth leaving this issue open for visibility too. It's what I do on my plugins :) I only close once the fix is merged and released.

I plan to release the next patch once #76 is merged.

> Thanks for the plugin! Have a good weekend!

No problem, and thanks, you too
