### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ModdedGamers** [famiu/feline.nvim#82]
**Neovim version**
NVIM v0.6.0-dev+227-gc1f573fbc 

**Feline version**
5d152e2

**Describe the bug**
I don't know what I'm doing

**To Reproduce**
1. Add this as a component:
<pre>
components.active[3][1] = {
	provider = function()
		local timer = vim.loop.new_timer()
		timer:start(0,1000,vim.schedule_wrap(function()
			return(os.date("%d %b %Y %H:%M:%S"))
		end))
	end,
}
</pre>
2. Reload neovim or run `:luafile %`.
3. You should see an error pop up

**Expected behavior**
I expected it to print the time in the bottom right in the bar. What am I doing wrong?

**Does this error occur in the minimal init file?**
Yes it does

**Screenshots**
![Screen Shot 2021-09-17 at 10 15 33](https://user-images.githubusercontent.com/35778371/133797670-153a5f3a-3077-451b-97a6-e198fe99165d.png)

**Additional context**
It's using an inline custom component, so maybe there's a parsing error with it?

**Comment by famiu** [comment]
The provider doesn't return any value. Timers cannot return values afaik. Also even then, you're not returning anything from the function itself. That's what you're doing wrong.

**Comment by ModdedGamers** [comment]
Then how do I get a function like this to work? I've tried using vimscript, but I can't wrap my head around it.

**Comment by famiu** [comment]
> Then how do I get a function like this to work? I've tried using vimscript, but I can't wrap my head around it.

I guess you can try make the provider return a local value and make the timer update the value
