### ISSUE TITLE
[Feature]Add winid to hl function 

### ISSUE THREAD

**Issue by kwkarlwang** [famiu/feline.nvim#84]
**Is your feature request related to a problem? Please describe.**
Hi, thanks for the plugin. I am currently trying to give different highlight to the filename depending if the file is modified. However, unlike provider which takes in `winid` as an argument, it seems like highlight function changes the highlighting globally for all statusbars for the buffers.

**Describe the solution you'd like**
I wish the highlight function can take in a winid as well, so that I am only modifying the statusbar for one particular buffer.

**Describe alternatives you've considered**
So inorder to achieve the different coloring, I use the `vim.bo.modified`. Here is my code.

```lua
table.insert(components.active, {})
table.insert(components.active, {})

table.insert(components.inactive, {})
table.insert(components.inactive, {})

local split = function(inputstr, sep)
	if sep == nil then
		sep = "%s"
	end
	local t = {}
	for str in string.gmatch(inputstr, "([^" .. sep .. "]+)") do
		table.insert(t, str)
	end
	return t
end

local ins_left = function(component)
	table.insert(components.active[1], component)
end
local ins_right = function(component)
	table.insert(components.active[#components.active], component)
end

local short_ins_left = function(component)
	table.insert(components.inactive[1], component)
end
local short_ins_right = function(component)
	table.insert(components.inactive[#components.active], component)
end
local file_path = {
	provider = function(_, winid)
		local filepath = vim.fn.fnamemodify(vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(winid)), ":~:.")
		local splitpath = split(filepath, "/")
		splitpath[#splitpath] = ""
		filepath = table.concat(splitpath, "/")
		return filepath
	end,
	hl = function()
		local res = {
			fg = colors.yellow,
			style = "bold",
		}
		if vim.bo.modifiable and vim.bo.modified then
			res.fg = colors.red
		end
		return res
	end,
}
ins_left(file_path)

local file_name = {
	provider = function(_, winid)
		return fn.fnamemodify(vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(winid)), ":t")
	end,
	hl = function()
		local res = {
			fg = colors.fg,
			style = "bold",
		}
		if vim.bo.modifiable and vim.bo.modified then
			res.fg = colors.red
		end
		return res
	end,
	icon = "",
}
ins_left(file_name)

short_ins_left(file_path)
short_ins_left(file_name)
```
However, this code not only modify the current buffer statusline, it also modifies other buffers as well. I think this can be solved with `vim.bo[bufnr].modified`, hence I wish there is an option for `winid`.

**Additional context**
Before modifying feline.lua buffer.
![image](https://user-images.githubusercontent.com/38927155/133895198-9aa87df9-2379-4f74-a57f-aff002ad2252.png)
After modifying feline.lua buffer.
![image](https://user-images.githubusercontent.com/38927155/133895225-38811667-98a4-418d-a2f4-98978cefb5da.png)
After jumping to galaxyline buffer and jumping back to feline.lua
![image](https://user-images.githubusercontent.com/38927155/133895253-08d3d7a5-4c7b-41f7-ab02-233ca4c295ca.png)

So the inactive buffer gets updated when trigger events happen, and the inactive buffer will be red when the active buffer is modified.

**Comment by famiu** [comment]
Seems like a valid usecase. Will be adding it soon

**Comment by famiu** [comment]
Does #89 work for you?

**Comment by famiu** [comment]
I'm going to close this since #89 was merged and this didn't autoclose for some reason. Please reopen if the issue still persists

**Comment by kwkarlwang** [comment]
#89 works like a charm! Thanks a lot! Now I think this is probably the first statusline I know that has this functionality.

There is one small problem. When the inactive buffer is the same file as the active buffer, after modifying active buffer, the inactive statusline does not seem like it will be updated. I assume this have something to do with trigger events? It is a rare case though, so I am perfectly fine with the way it is now.
![image](https://user-images.githubusercontent.com/38927155/133935911-b14b64ed-9792-4dba-a83d-129d3dd410d0.png)

**Comment by famiu** [comment]
> #89 works like a charm! Thanks a lot! Now I think this is probably the first statusline I know that has this functionality.
> 
> There is one small problem. When the inactive buffer is the same file as the active buffer, after modifying active buffer, the inactive statusline does not seem like it will be updated. I assume this have something to do with trigger events? It is a rare case though, so I am perfectly fine with the way it is now.
> ![image](https://user-images.githubusercontent.com/38927155/133935911-b14b64ed-9792-4dba-a83d-129d3dd410d0.png)

It does have to do with trigger events, see `update_triggers` in [the setup function](https://github.com/famiu/feline.nvim#setup-function)

**Comment by kwkarlwang** [comment]
> > #89 works like a charm! Thanks a lot! Now I think this is probably the first statusline I know that has this functionality.
> > There is one small problem. When the inactive buffer is the same file as the active buffer, after modifying active buffer, the inactive statusline does not seem like it will be updated. I assume this have something to do with trigger events? It is a rare case though, so I am perfectly fine with the way it is now.
> > ![image](https://user-images.githubusercontent.com/38927155/133935911-b14b64ed-9792-4dba-a83d-129d3dd410d0.png)
> 
> It does have to do with trigger events, see `update_triggers` in [the setup function](https://github.com/famiu/feline.nvim#setup-function)
```lua
	update_triggers = { "VimEnter", "WinEnter", "WinClosed", "FileChangedShellPost", "BufModifiedSet" }
```
Perfect! Now this is configured to exactly how I wanted. Thanks again for the great plugin!

**Comment by famiu** [comment]
> Perfect! Now this is configured to exactly how I wanted. Thanks again for the great plugin!

Np :)
