### ISSUE TITLE
[Feature] Add a configuration option for the file modified icon

### ISSUE THREAD

**Issue by gblock0** [famiu/feline.nvim#9]
I'm loving this plugin! The documentation is excellent. 

Currently, it seems like the `circle` icon is the only option to show that a file is modified. What do you think about adding a configuration option to allow the `circle` to be overwritten?

Not sure how you'd prefer to implement it, but I'd be happy to update the provider. I was thinking of adding a component option like `file_modified_icon`, but then the `component` table gets polluted just for `file_info`.

**Comment by famiu** [comment]
You can change the file modified icon using the `file_modified_icon` component value now
