### ISSUE TITLE
Allow wildcard character in setup function

### ISSUE THREAD

**Issue by Pyther99** [famiu/feline.nvim#91]
**Is your feature request related to a problem? Please describe.**
I would like to disable feline in all windows of nvim-dap-ui.

**Describe the solution you'd like**
I would like for feline to treat wildcard characters in the setup function properly:
`disable = { filetypes = { "dapui*" } }`

**Comment by famiu** [comment]
The best I can do is use Lua's pattern matching in which case the "wildcard" would be more like `"dapui.*"`, would that be fine?

**Comment by Pyther99** [comment]
> The best I can do is use Lua's pattern matching in which case the "wildcard" would be more like `"dapui.*"`, would that be fine?

Sure, that would be great!

**Comment by famiu** [comment]
Can you please check if #92 does what you need

**Comment by Pyther99** [comment]
Yes, the changes work perfectly
