### ISSUE TITLE
[Feature] make every function accept (component, winid)

### ISSUE THREAD

**Issue by rebelot** [famiu/feline.nvim#97]
because the statusline is evaluated in the current window and buffer with `%!`, every function, whether it is a provider, hl, icon, or separator, should have a handler to its original window, otherwise, doing something like

```lua
FileName = {
  provider = function(component, winid),
    return vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(winid)) 
  end,
  hl = function()
    if vim.bo.modified then return {fg = 'magenta', style = 'bold', name = 'StatusFileNameModified'}
    else return {fg = 'purple', style = 'bold', name = 'StatusFileName'}
    end 
  end
} 
```
will not work, in the sense that the current buffer modified status will affect all the statuslines that display the `FileName` component.

A workaround would be to set every field of the component from within the provider function, like this:
```lua
FileName = {
  provider = function(component, winid),
    if vim.bo[winid].modified then component.hl = {fg = 'magenta', style = 'bold', name = 'StatusFileNameModified'}
    else component.hl = {fg = 'purple', style = 'bold', name = 'StatusFileName'}
    end
    return vim.api.nvim_buf_get_name(vim.api.nvim_win_get_buf(winid))
  end,
} 
```
but I think it's not very elegant, considering the plugin phylosophy. Also, the README.md should be clearer about functions being evaluated in the current window context (`%!`)

**Comment by ram02z** [comment]
This feature was recently added to the develop branch. See https://github.com/famiu/feline.nvim/commit/20172e8f20076c08911bc49b602f3a9463843b0b
